// Real VDMBio product data — replace with scraper output for full 700+ catalog
import type { Product } from '@/types'

export const ALL_PRODUCTS: Product[] = [
  // ── APOPTOSIS ──────────────────────────────────────────────────────────
  { id:'1', name:'Z-VAD(OMe)-FMK', slug:'z-vadome-fmk', catalog_number:'VD-NP-0073', cas_number:'187389-52-2', formula:'C25H34FN3O9', molecular_weight:'555.6', purity:'HPLC-98%', appearance:'White to off-white solid', solubility:'DMSO', storage:'-20°C', synonyms:'Pan-caspase inhibitor', description:'A cell-permeable irreversible pan-caspase inhibitor widely used in apoptosis research.', category_id:'2', image_url:null, price_min:85, price_max:320, created_at:'' },
  { id:'2', name:'Q-VD-OPH', slug:'q-vd-oph', catalog_number:'VD-NP-0067', cas_number:'1135695-98-5', formula:'C26H25FN4O5', molecular_weight:'512.49', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'Quinoline-Val-Asp(OMe)-CH2-OPh', description:'Broad-spectrum cell-permeable caspase inhibitor with low toxicity.', category_id:'2', image_url:null, price_min:95, price_max:380, created_at:'' },
  { id:'3', name:'Salubrinal', slug:'salubrinal', catalog_number:'VD-OEIA-0277', cas_number:'1203494-61-4', formula:'C21H17Cl3N4OS', molecular_weight:'480.8', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:null, description:'Selective inhibitor of eIF2α dephosphorylation, protecting cells from ER stress.', category_id:'4', image_url:null, price_min:60, price_max:240, created_at:'' },
  { id:'4', name:'Ac-DEVD-CHO', slug:'ac-devd-cho', catalog_number:'VD-NP-0002', cas_number:'169332-60-9', formula:'C22H32N4O9', molecular_weight:'500.51', purity:'HPLC-97%', appearance:'White powder', solubility:'DMSO', storage:'-20°C', synonyms:'Caspase-3 inhibitor I', description:'Reversible tetrapeptide inhibitor of caspase-3.', category_id:'2', image_url:null, price_min:75, price_max:290, created_at:'' },
  { id:'5', name:'Z-DEVD-FMK', slug:'z-devd-fmk', catalog_number:'VD-NP-0043', cas_number:'179474-81-2', formula:'C29H37FN4O9', molecular_weight:'612.62', purity:'HPLC-97%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:null, description:'Irreversible caspase-3 inhibitor; cell-permeable.', category_id:'2', image_url:null, price_min:80, price_max:310, created_at:'' },
  { id:'6', name:'Z-IETD-FMK', slug:'z-ietd-fmk', catalog_number:'VD-NP-0060', cas_number:'210344-98-2', formula:'C34H46FN5O10', molecular_weight:'709.75', purity:'HPLC-97%', appearance:'White powder', solubility:'DMSO', storage:'-20°C', synonyms:'Caspase-8 inhibitor', description:'Irreversible selective inhibitor of caspase-8.', category_id:'2', image_url:null, price_min:80, price_max:310, created_at:'' },
  { id:'7', name:'Z-LEHD-FMK', slug:'z-lehd-fmk', catalog_number:'VD-NP-0065', cas_number:'218600-53-4', formula:'C34H50FN5O11', molecular_weight:'727.78', purity:'HPLC-97%', appearance:'White powder', solubility:'DMSO', storage:'-20°C', synonyms:'Caspase-9 inhibitor', description:'Irreversible selective inhibitor of caspase-9.', category_id:'2', image_url:null, price_min:80, price_max:310, created_at:'' },
  { id:'8', name:'Staurosporine', slug:'staurosporine', catalog_number:'VD-NP-0288', cas_number:'62996-74-1', formula:'C28H26N4O3', molecular_weight:'466.54', purity:'HPLC-98%', appearance:'Off-white solid', solubility:'DMSO', storage:'-20°C', synonyms:'AM-2282', description:'Potent protein kinase inhibitor used to induce apoptosis.', category_id:'2', image_url:null, price_min:55, price_max:210, created_at:'' },
  // ── ENZYME INHIBITORS ───────────────────────────────────────────────────
  { id:'9', name:'SANT-1', slug:'sant-1', catalog_number:'VD-OEIA-0059', cas_number:'304909-07-7', formula:'C25H21N3O3', molecular_weight:'415.45', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'Hedgehog antagonist', description:'Potent Hedgehog pathway antagonist targeting the Smoothened receptor.', category_id:'4', image_url:null, price_min:85, price_max:320, created_at:'' },
  { id:'10', name:'(-)-Actinonin', slug:'actinonin', catalog_number:'VD-OEIA-0021', cas_number:'13434-13-4', formula:'C19H35N3O5', molecular_weight:'385.5', purity:'HPLC-98%', appearance:'Off-white solid', solubility:'DMSO', storage:'+4°C', synonyms:null, description:'Naturally occurring antibiotic and metalloprotease inhibitor.', category_id:'4', image_url:null, price_min:55, price_max:220, created_at:'' },
  { id:'11', name:'Y-27632 dihydrochloride', slug:'y-27632-dihydrochloride', catalog_number:'VD-OEIA-0323', cas_number:'146986-50-7', formula:'C14H21N3O·2HCl', molecular_weight:'320.26', purity:'HPLC-98%', appearance:'White solid', solubility:'Water', storage:'-20°C', synonyms:'ROCK inhibitor', description:'Selective ROCK (Rho-associated coiled-coil kinase) inhibitor.', category_id:'4', image_url:null, price_min:65, price_max:250, created_at:'' },
  { id:'12', name:'PD98059', slug:'pd98059', catalog_number:'VD-OEIA-0228', cas_number:'167869-21-8', formula:'C16H13NO3', molecular_weight:'267.28', purity:'HPLC-98%', appearance:'Yellow solid', solubility:'DMSO', storage:'-20°C', synonyms:'MEK1 inhibitor', description:'Selective MEK1/2 inhibitor; blocks ERK activation.', category_id:'4', image_url:null, price_min:60, price_max:235, created_at:'' },
  { id:'13', name:'SB203580', slug:'sb203580', catalog_number:'VD-OEIA-0265', cas_number:'152121-47-6', formula:'C21H16FN3OS', molecular_weight:'377.43', purity:'HPLC-98%', appearance:'Yellow solid', solubility:'DMSO', storage:'-20°C', synonyms:'p38 MAPK inhibitor', description:'Potent and selective p38 MAP kinase inhibitor.', category_id:'4', image_url:null, price_min:65, price_max:250, created_at:'' },
  { id:'14', name:'LY294002', slug:'ly294002', catalog_number:'VD-OEIA-0175', cas_number:'154447-36-6', formula:'C19H17NO3', molecular_weight:'307.35', purity:'HPLC-98%', appearance:'Yellow solid', solubility:'DMSO', storage:'-20°C', synonyms:'PI3K inhibitor', description:'Selective phosphatidylinositol 3-kinase (PI3K) inhibitor.', category_id:'4', image_url:null, price_min:55, price_max:210, created_at:'' },
  { id:'15', name:'Rapamycin', slug:'rapamycin', catalog_number:'VD-OEIA-0248', cas_number:'53123-88-9', formula:'C51H79NO13', molecular_weight:'914.17', purity:'HPLC-98%', appearance:'White powder', solubility:'Ethanol', storage:'-20°C', synonyms:'Sirolimus', description:'mTOR inhibitor; immunosuppressant and anticancer agent.', category_id:'4', image_url:null, price_min:90, price_max:360, created_at:'' },
  { id:'16', name:'Wortmannin', slug:'wortmannin', catalog_number:'VD-OEIA-0315', cas_number:'19545-26-7', formula:'C19H18O8', molecular_weight:'378.35', purity:'HPLC-98%', appearance:'Yellow solid', solubility:'DMSO', storage:'-20°C', synonyms:null, description:'Potent and irreversible PI3K inhibitor.', category_id:'4', image_url:null, price_min:60, price_max:230, created_at:'' },
  { id:'17', name:'Roscovitine', slug:'roscovitine', catalog_number:'VD-OEIA-0257', cas_number:'186692-46-6', formula:'C19H26N6', molecular_weight:'354.45', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'CYC202; Seliciclib', description:'Potent CDK inhibitor (CDK1, CDK2, CDK5, CDK7, CDK9).', category_id:'4', image_url:null, price_min:70, price_max:270, created_at:'' },
  { id:'18', name:'Flavopiridol', slug:'flavopiridol', catalog_number:'VD-OEIA-0112', cas_number:'146426-40-6', formula:'C21H20ClNO5', molecular_weight:'401.84', purity:'HPLC-98%', appearance:'Yellow solid', solubility:'DMSO', storage:'-20°C', synonyms:'Alvocidib', description:'Pan-CDK inhibitor with anticancer activity.', category_id:'4', image_url:null, price_min:75, price_max:290, created_at:'' },
  // ── CANCER RESEARCH ─────────────────────────────────────────────────────
  { id:'19', name:'(±)-Thalidomide', slug:'thalidomide', catalog_number:'VD-AM-0111', cas_number:'50-35-1', formula:'C13H10N2O4', molecular_weight:'258.23', purity:'HPLC-98%', appearance:'White Solid', solubility:'DMSO', storage:'-20°C', synonyms:null, description:'Immunomodulatory drug; used in multiple myeloma research.', category_id:'3', image_url:null, price_min:75, price_max:280, created_at:'' },
  { id:'20', name:'(±)-AMG 487', slug:'amg-487', catalog_number:'VD-AM-0057', cas_number:'473719-41-4', formula:'C32H28F3N5O4', molecular_weight:'623.59', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'CXCR3 antagonist', description:'Selective CXCR3 antagonist; antitumor and antimetastatic activity.', category_id:'3', image_url:null, price_min:90, price_max:350, created_at:'' },
  { id:'21', name:'Camptothecin', slug:'camptothecin', catalog_number:'VD-AM-0088', cas_number:'7689-03-4', formula:'C20H16N2O4', molecular_weight:'348.36', purity:'HPLC-98%', appearance:'Yellow solid', solubility:'DMSO', storage:'-20°C', synonyms:null, description:'Topoisomerase I inhibitor; anticancer alkaloid.', category_id:'3', image_url:null, price_min:55, price_max:210, created_at:'' },
  { id:'22', name:'Etoposide', slug:'etoposide', catalog_number:'VD-AM-0100', cas_number:'33419-42-0', formula:'C29H32O13', molecular_weight:'588.56', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'VP-16', description:'Topoisomerase II inhibitor used in cancer chemotherapy.', category_id:'3', image_url:null, price_min:45, price_max:175, created_at:'' },
  { id:'23', name:'Docetaxel', slug:'docetaxel', catalog_number:'VD-AM-0096', cas_number:'114977-28-5', formula:'C43H53NO14', molecular_weight:'807.88', purity:'HPLC-98%', appearance:'White powder', solubility:'Ethanol', storage:'-20°C', synonyms:'Taxotere', description:'Taxane chemotherapy agent; stabilizes microtubules.', category_id:'3', image_url:null, price_min:80, price_max:310, created_at:'' },
  { id:'24', name:'Paclitaxel', slug:'paclitaxel', catalog_number:'VD-AM-0126', cas_number:'33069-62-4', formula:'C47H51NO14', molecular_weight:'853.91', purity:'HPLC-98%', appearance:'White powder', solubility:'DMSO', storage:'-20°C', synonyms:'Taxol', description:'Mitotic inhibitor; promotes tubulin polymerization.', category_id:'3', image_url:null, price_min:55, price_max:210, created_at:'' },
  { id:'25', name:'Doxorubicin HCl', slug:'doxorubicin-hcl', catalog_number:'VD-AM-0097', cas_number:'25316-40-9', formula:'C27H29NO11·HCl', molecular_weight:'579.99', purity:'HPLC-98%', appearance:'Red/orange solid', solubility:'Water', storage:'-20°C', synonyms:'Adriamycin', description:'Anthracycline antibiotic; DNA intercalating anticancer agent.', category_id:'3', image_url:null, price_min:50, price_max:190, created_at:'' },
  { id:'26', name:'5-Fluorouracil', slug:'5-fluorouracil', catalog_number:'VD-AM-0056', cas_number:'51-21-8', formula:'C4H3FN2O2', molecular_weight:'130.08', purity:'HPLC-98%', appearance:'White solid', solubility:'Water', storage:'RT', synonyms:'5-FU', description:'Pyrimidine analog; thymidylate synthase inhibitor.', category_id:'3', image_url:null, price_min:30, price_max:115, created_at:'' },
  { id:'27', name:'Cisplatin', slug:'cisplatin', catalog_number:'VD-AM-0090', cas_number:'15663-27-1', formula:'Cl2H6N2Pt', molecular_weight:'300.05', purity:'HPLC-98%', appearance:'Yellow powder', solubility:'Water/DMF', storage:'RT', synonyms:'CDDP', description:'Platinum-based chemotherapy drug; DNA crosslinker.', category_id:'3', image_url:null, price_min:35, price_max:135, created_at:'' },
  { id:'28', name:'Bortezomib', slug:'bortezomib', catalog_number:'VD-AM-0083', cas_number:'179324-69-7', formula:'C19H25BN4O4', molecular_weight:'384.24', purity:'HPLC-98%', appearance:'White powder', solubility:'DMSO', storage:'-20°C', synonyms:'Velcade; PS-341', description:'Proteasome inhibitor; first-in-class anticancer drug.', category_id:'3', image_url:null, price_min:70, price_max:270, created_at:'' },
  // ── ANTIVIRALS ──────────────────────────────────────────────────────────
  { id:'29', name:'Acyclovir', slug:'acyclovir', catalog_number:'VD-AV-0001', cas_number:'59277-89-3', formula:'C8H11N5O3', molecular_weight:'225.21', purity:'HPLC-98%', appearance:'White powder', solubility:'0.1N NaOH', storage:'RT', synonyms:'Aciclovir; Zovirax', description:'Antiviral nucleoside analog; active against herpes viruses.', category_id:'1', image_url:null, price_min:30, price_max:115, created_at:'' },
  { id:'30', name:'Zidovudine', slug:'zidovudine', catalog_number:'VD-AV-0045', cas_number:'30516-87-1', formula:'C10H13N5O4', molecular_weight:'267.24', purity:'HPLC-98%', appearance:'White solid', solubility:'Water', storage:'RT', synonyms:'AZT; Retrovir', description:'Nucleoside reverse transcriptase inhibitor; antiretroviral drug.', category_id:'1', image_url:null, price_min:35, price_max:135, created_at:'' },
  { id:'31', name:'Ribavirin', slug:'ribavirin', catalog_number:'VD-AV-0035', cas_number:'36791-04-5', formula:'C8H12N4O5', molecular_weight:'244.20', purity:'HPLC-98%', appearance:'White powder', solubility:'Water', storage:'RT', synonyms:'Virazole', description:'Broad-spectrum antiviral nucleoside analog.', category_id:'1', image_url:null, price_min:35, price_max:135, created_at:'' },
  { id:'32', name:'Oseltamivir phosphate', slug:'oseltamivir-phosphate', catalog_number:'VD-AV-0033', cas_number:'204255-11-8', formula:'C16H28N2O4·H3PO4', molecular_weight:'410.40', purity:'HPLC-98%', appearance:'White solid', solubility:'Water', storage:'RT', synonyms:'Tamiflu', description:'Neuraminidase inhibitor; influenza antiviral.', category_id:'1', image_url:null, price_min:50, price_max:195, created_at:'' },
  { id:'33', name:'Remdesivir', slug:'remdesivir', catalog_number:'VD-AV-0034', cas_number:'1809249-37-3', formula:'C27H35N6O8P', molecular_weight:'602.58', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'GS-5734', description:'Nucleotide prodrug antiviral; broad-spectrum RNA virus inhibitor.', category_id:'1', image_url:null, price_min:110, price_max:430, created_at:'' },
  { id:'34', name:'Lopinavir', slug:'lopinavir', catalog_number:'VD-AV-0025', cas_number:'192725-17-0', formula:'C37H48N4O5', molecular_weight:'628.80', purity:'HPLC-98%', appearance:'White powder', solubility:'DMSO', storage:'-20°C', synonyms:'ABT-378', description:'HIV protease inhibitor used in antiretroviral therapy.', category_id:'1', image_url:null, price_min:75, price_max:290, created_at:'' },
  // ── ANTIBIOTICS ─────────────────────────────────────────────────────────
  { id:'35', name:'Puromycin dihydrochloride', slug:'puromycin-dihydrochloride', catalog_number:'VD-AB-0022', cas_number:'58-58-2', formula:'C22H29N7O5·2HCl', molecular_weight:'544.42', purity:'HPLC-98%', appearance:'White to off-white powder', solubility:'Water', storage:'-20°C', synonyms:null, description:'Aminonucleoside antibiotic; used as cell selection agent.', category_id:'5', image_url:null, price_min:40, price_max:155, created_at:'' },
  { id:'36', name:'Hygromycin B', slug:'hygromycin-b', catalog_number:'VD-AB-0012', cas_number:'31282-04-9', formula:'C20H37N3O13', molecular_weight:'527.52', purity:'HPLC-95%', appearance:'White powder', solubility:'Water', storage:'-20°C', synonyms:null, description:'Aminoglycoside antibiotic; widely used selectable marker.', category_id:'5', image_url:null, price_min:55, price_max:210, created_at:'' },
  { id:'37', name:'Blasticidin S HCl', slug:'blasticidin-s-hcl', catalog_number:'VD-AB-0003', cas_number:'3513-03-9', formula:'C17H26N8O5·HCl', molecular_weight:'458.90', purity:'HPLC-95%', appearance:'White powder', solubility:'Water', storage:'-20°C', synonyms:null, description:'Nucleoside antibiotic; mammalian cell selection agent.', category_id:'5', image_url:null, price_min:45, price_max:175, created_at:'' },
  { id:'38', name:'G418 Sulfate', slug:'g418-sulfate', catalog_number:'VD-AB-0009', cas_number:'108321-42-2', formula:'C20H40N4O10·2H2SO4', molecular_weight:'692.71', purity:'HPLC-95%', appearance:'Off-white powder', solubility:'Water', storage:'-20°C', synonyms:'Geneticin', description:'Aminoglycoside antibiotic used for stable cell selection.', category_id:'5', image_url:null, price_min:50, price_max:190, created_at:'' },
  // ── AMINO ACIDS / INTERMEDIATES ─────────────────────────────────────────
  { id:'39', name:'H-Hyp-OH', slug:'h-hyp-oh', catalog_number:'VD-UAA-0238', cas_number:'51-35-4', formula:'C5H9NO3', molecular_weight:'131.13', purity:'HPLC-98%', appearance:'White crystalline powder', solubility:'Water', storage:'-20°C', synonyms:'(2S,4R)-4-hydroxypyrrolidine-2-carboxylic acid', description:'Hydroxyproline amino acid derivative; collagen biosynthesis.', category_id:'9', image_url:null, price_min:180, price_max:800, created_at:'' },
  { id:'40', name:'Boc-Asp(OtBu)-OH', slug:'boc-asp-otbu-oh', catalog_number:'VD-UAA-0050', cas_number:'13726-67-5', formula:'C13H23NO6', molecular_weight:'289.33', purity:'HPLC-98%', appearance:'White powder', solubility:'DCM', storage:'RT', synonyms:null, description:'Boc-protected aspartic acid derivative for solid-phase peptide synthesis.', category_id:'9', image_url:null, price_min:50, price_max:200, created_at:'' },
  { id:'41', name:'Fmoc-Lys(Boc)-OH', slug:'fmoc-lys-boc-oh', catalog_number:'VD-UAA-0191', cas_number:'71989-26-9', formula:'C26H32N2O6', molecular_weight:'468.54', purity:'HPLC-98%', appearance:'White powder', solubility:'DMF', storage:'RT', synonyms:null, description:'Fmoc-protected lysine for automated solid-phase peptide synthesis.', category_id:'9', image_url:null, price_min:65, price_max:250, created_at:'' },
  { id:'42', name:'H-Glu(OtBu)-OH', slug:'h-glu-otbu-oh', catalog_number:'VD-UAA-0193', cas_number:'2419-56-9', formula:'C9H17NO4', molecular_weight:'203.24', purity:'HPLC-98%', appearance:'White crystalline powder', solubility:'Water', storage:'RT', synonyms:null, description:'Glutamic acid mono-tert-butyl ester; peptide synthesis.', category_id:'9', image_url:null, price_min:45, price_max:175, created_at:'' },
  // ── DNA DAMAGE ──────────────────────────────────────────────────────────
  { id:'43', name:'Hydroxyurea', slug:'hydroxyurea', catalog_number:'VD-DD-0008', cas_number:'127-07-1', formula:'CH4N2O2', molecular_weight:'76.05', purity:'HPLC-99%', appearance:'White crystalline solid', solubility:'Water', storage:'RT', synonyms:null, description:'Ribonucleotide reductase inhibitor; DNA synthesis inhibitor.', category_id:'6', image_url:null, price_min:25, price_max:95, created_at:'' },
  { id:'44', name:'KU-55933', slug:'ku-55933', catalog_number:'VD-DD-0011', cas_number:'587871-26-9', formula:'C19H19NO4S2', molecular_weight:'393.49', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'ATM kinase inhibitor', description:'Potent and selective ATM kinase inhibitor.', category_id:'6', image_url:null, price_min:80, price_max:310, created_at:'' },
  { id:'45', name:'Olaparib', slug:'olaparib', catalog_number:'VD-DD-0017', cas_number:'763113-22-0', formula:'C24H23FN4O3', molecular_weight:'434.46', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'AZD2281; Lynparza', description:'PARP inhibitor; approved for BRCA-mutated cancers.', category_id:'6', image_url:null, price_min:90, price_max:350, created_at:'' },
  // ── HEDGEHOG / SMOOTHENED ───────────────────────────────────────────────
  { id:'46', name:'Vismodegib', slug:'vismodegib', catalog_number:'VD-HH-0004', cas_number:'879085-55-9', formula:'C14H14Cl2N2O3S', molecular_weight:'421.29', purity:'HPLC-98%', appearance:'Off-white solid', solubility:'DMSO', storage:'-20°C', synonyms:'GDC-0449; Erivedge', description:'First SMO inhibitor approved for basal cell carcinoma.', category_id:'3', image_url:null, price_min:85, price_max:330, created_at:'' },
  { id:'47', name:'Cyclopamine', slug:'cyclopamine', catalog_number:'VD-HH-0001', cas_number:'4449-51-8', formula:'C27H41NO2', molecular_weight:'411.62', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'11-deoxojervine', description:'Naturally occurring Hedgehog signaling inhibitor; teratogenic alkaloid.', category_id:'3', image_url:null, price_min:75, price_max:290, created_at:'' },
  { id:'48', name:'Smoothened Agonist (SAG)', slug:'smoothened-agonist-sag', catalog_number:'VD-HH-0003', cas_number:'364590-63-6', formula:'C25H34ClN5O2S', molecular_weight:'536.09', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'Hh-Ag 1.1', description:'Small molecule agonist of Smoothened; activates Hedgehog signaling.', category_id:'3', image_url:null, price_min:90, price_max:350, created_at:'' },
  // ── EPIGENETICS ─────────────────────────────────────────────────────────
  { id:'49', name:'Trichostatin A', slug:'trichostatin-a', catalog_number:'VD-EP-0012', cas_number:'58880-19-6', formula:'C17H22N2O3', molecular_weight:'302.37', purity:'HPLC-98%', appearance:'Yellow solid', solubility:'DMSO', storage:'-20°C', synonyms:'TSA', description:'Histone deacetylase (HDAC) inhibitor.', category_id:'4', image_url:null, price_min:65, price_max:250, created_at:'' },
  { id:'50', name:'Vorinostat', slug:'vorinostat', catalog_number:'VD-EP-0015', cas_number:'149647-78-9', formula:'C14H20N2O3', molecular_weight:'264.32', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'RT', synonyms:'SAHA; Zolinza', description:'HDAC inhibitor approved for cutaneous T cell lymphoma.', category_id:'4', image_url:null, price_min:50, price_max:190, created_at:'' },
  { id:'51', name:'5-Azacytidine', slug:'5-azacytidine', catalog_number:'VD-EP-0001', cas_number:'320-67-2', formula:'C8H12N4O5', molecular_weight:'244.20', purity:'HPLC-98%', appearance:'White solid', solubility:'Water', storage:'-20°C', synonyms:'Vidaza; Azacitidine', description:'DNA methyltransferase inhibitor; epigenetic drug.', category_id:'3', image_url:null, price_min:40, price_max:155, created_at:'' },
  { id:'52', name:'Decitabine', slug:'decitabine', catalog_number:'VD-EP-0003', cas_number:'2353-33-5', formula:'C8H11N3O4', molecular_weight:'228.20', purity:'HPLC-98%', appearance:'White solid', solubility:'Water', storage:'-20°C', synonyms:'5-Aza-2-deoxycytidine; Dacogen', description:'DNA methylation inhibitor; used in MDS/AML research.', category_id:'3', image_url:null, price_min:45, price_max:175, created_at:'' },
  // ── RECEPTOR MODULATORS ─────────────────────────────────────────────────
  { id:'53', name:'(±)-ISCK03', slug:'isck03', catalog_number:'VD-OEIA-0148', cas_number:'1197300-24-5', formula:'C20H20N4O2S', molecular_weight:'396.46', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'Stem-cell factor/c-Kit inhibitor', description:'Selective c-Kit (SCF receptor) tyrosine kinase inhibitor.', category_id:'4', image_url:null, price_min:80, price_max:310, created_at:'' },
  { id:'54', name:'SU5402', slug:'su5402', catalog_number:'VD-OEIA-0289', cas_number:'215543-92-3', formula:'C17H18N2O3', molecular_weight:'298.34', purity:'HPLC-98%', appearance:'Yellow solid', solubility:'DMSO', storage:'-20°C', synonyms:'FGFR inhibitor', description:'Potent PDGFR and FGFR tyrosine kinase inhibitor.', category_id:'4', image_url:null, price_min:75, price_max:290, created_at:'' },
  { id:'55', name:'Imatinib mesylate', slug:'imatinib-mesylate', catalog_number:'VD-OEIA-0143', cas_number:'220127-57-1', formula:'C29H31N7O·CH4SO3', molecular_weight:'589.71', purity:'HPLC-98%', appearance:'White to off-white solid', solubility:'Water', storage:'RT', synonyms:'Gleevec; STI571', description:'BCR-ABL tyrosine kinase inhibitor; anticancer drug.', category_id:'3', image_url:null, price_min:55, price_max:210, created_at:'' },
  { id:'56', name:'Gefitinib', slug:'gefitinib', catalog_number:'VD-OEIA-0117', cas_number:'184475-35-2', formula:'C22H24ClFN4O3', molecular_weight:'446.90', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'Iressa; ZD1839', description:'EGFR tyrosine kinase inhibitor; non-small cell lung cancer treatment.', category_id:'3', image_url:null, price_min:65, price_max:250, created_at:'' },
  { id:'57', name:'Erlotinib HCl', slug:'erlotinib-hcl', catalog_number:'VD-OEIA-0099', cas_number:'183319-69-9', formula:'C22H23N3O4·HCl', molecular_weight:'429.90', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'Tarceva; OSI-774', description:'EGFR/HER1 tyrosine kinase inhibitor.', category_id:'3', image_url:null, price_min:65, price_max:250, created_at:'' },
  // ── NEUROSCIENCE / CHOLINERGICS ─────────────────────────────────────────
  { id:'58', name:'Donepezil HCl', slug:'donepezil-hcl', catalog_number:'VD-CH-0003', cas_number:'120011-70-3', formula:'C24H29NO3·HCl', molecular_weight:'415.95', purity:'HPLC-98%', appearance:'White solid', solubility:'Water', storage:'RT', synonyms:'Aricept; E2020', description:'Acetylcholinesterase inhibitor; Alzheimer treatment research.', category_id:'7', image_url:null, price_min:40, price_max:155, created_at:'' },
  { id:'59', name:'Rivastigmine tartrate', slug:'rivastigmine-tartrate', catalog_number:'VD-CH-0009', cas_number:'129101-54-8', formula:'C14H22N2O2·C4H6O6', molecular_weight:'400.43', purity:'HPLC-98%', appearance:'White solid', solubility:'Water', storage:'RT', synonyms:'Exelon', description:'Reversible AChE inhibitor; Parkinson/Alzheimer research.', category_id:'7', image_url:null, price_min:40, price_max:155, created_at:'' },
  // ── ANTICOAGULANTS ──────────────────────────────────────────────────────
  { id:'60', name:'Warfarin sodium', slug:'warfarin-sodium', catalog_number:'VD-AC-0005', cas_number:'129-06-6', formula:'C19H15NaO4', molecular_weight:'330.31', purity:'HPLC-98%', appearance:'White amorphous powder', solubility:'Water', storage:'RT', synonyms:'Coumadin', description:'Vitamin K epoxide reductase inhibitor; anticoagulant.', category_id:'8', image_url:null, price_min:30, price_max:115, created_at:'' },
  { id:'61', name:'Heparin sodium', slug:'heparin-sodium', catalog_number:'VD-AC-0002', cas_number:'9041-08-1', formula:'(C12H19NO20S3)n·Na', molecular_weight:null, purity:'≥180 IU/mg', appearance:'White to off-white powder', solubility:'Water', storage:'RT', synonyms:null, description:'Anticoagulant glycosaminoglycan; prevents thrombus formation.', category_id:'8', image_url:null, price_min:35, price_max:135, created_at:'' },
  // ── HISTAMINERGICS ──────────────────────────────────────────────────────
  { id:'62', name:'Histamine dihydrochloride', slug:'histamine-dihydrochloride', catalog_number:'VD-HI-0002', cas_number:'56-92-8', formula:'C5H9N3·2HCl', molecular_weight:'184.07', purity:'HPLC-99%', appearance:'White crystalline solid', solubility:'Water', storage:'RT', synonyms:null, description:'Biogenic amine; H1/H2/H3 receptor agonist.', category_id:'10', image_url:null, price_min:25, price_max:95, created_at:'' },
  { id:'63', name:'Cimetidine', slug:'cimetidine', catalog_number:'VD-HI-0001', cas_number:'51481-61-9', formula:'C10H16N6S', molecular_weight:'252.34', purity:'HPLC-99%', appearance:'White solid', solubility:'Water', storage:'RT', synonyms:'Tagamet', description:'H2 receptor antagonist; gastric acid suppressor.', category_id:'10', image_url:null, price_min:25, price_max:95, created_at:'' },
  // ── INORGANICS ──────────────────────────────────────────────────────────
  { id:'64', name:'Sodium orthovanadate', slug:'sodium-orthovanadate', catalog_number:'VD-IN-0003', cas_number:'13721-39-6', formula:'Na3VO4', molecular_weight:'183.94', purity:'≥98%', appearance:'White solid', solubility:'Water', storage:'RT', synonyms:'Na3VO4', description:'Protein tyrosine phosphatase inhibitor.', category_id:'11', image_url:null, price_min:20, price_max:75, created_at:'' },
  { id:'65', name:'Sodium fluoride', slug:'sodium-fluoride', catalog_number:'VD-IN-0002', cas_number:'7681-49-4', formula:'NaF', molecular_weight:'41.99', purity:'≥99%', appearance:'White powder', solubility:'Water', storage:'RT', synonyms:null, description:'Serine/threonine phosphatase inhibitor; used in cell signaling research.', category_id:'11', image_url:null, price_min:15, price_max:55, created_at:'' },
  // ── GROWTH FACTORS / SIGNALING ──────────────────────────────────────────
  { id:'66', name:'CHIR99021', slug:'chir99021', catalog_number:'VD-OEIA-0072', cas_number:'252917-06-9', formula:'C22H18Cl2N8', molecular_weight:'465.34', purity:'HPLC-98%', appearance:'Orange solid', solubility:'DMSO', storage:'-20°C', synonyms:'CT99021; GSK3 inhibitor', description:'Potent and selective GSK-3α/β inhibitor.', category_id:'4', image_url:null, price_min:70, price_max:270, created_at:'' },
  { id:'67', name:'SB431542', slug:'sb431542', catalog_number:'VD-OEIA-0264', cas_number:'301836-41-9', formula:'C22H18N4O3', molecular_weight:'390.41', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'ALK5 inhibitor', description:'Potent selective inhibitor of TGF-β type I receptor (ALK5).', category_id:'4', image_url:null, price_min:70, price_max:270, created_at:'' },
  { id:'68', name:'Dorsomorphin', slug:'dorsomorphin', catalog_number:'VD-OEIA-0092', cas_number:'866405-64-3', formula:'C24H25N5O', molecular_weight:'415.50', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'Compound C; BMP inhibitor', description:'Selective AMPK inhibitor; also inhibits BMP signaling.', category_id:'4', image_url:null, price_min:75, price_max:290, created_at:'' },
  { id:'69', name:'Forskolin', slug:'forskolin', catalog_number:'VD-OEIA-0113', cas_number:'66575-29-9', formula:'C22H34O7', molecular_weight:'410.50', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:null, description:'Adenylyl cyclase activator; raises intracellular cAMP.', category_id:'4', image_url:null, price_min:60, price_max:230, created_at:'' },
  { id:'70', name:'Retinoic acid', slug:'retinoic-acid', catalog_number:'VD-OEIA-0251', cas_number:'302-79-4', formula:'C20H28O2', molecular_weight:'300.44', purity:'HPLC-98%', appearance:'Yellow crystals', solubility:'DMSO', storage:'-20°C', synonyms:'All-trans retinoic acid; ATRA; Tretinoin', description:'Vitamin A acid; nuclear retinoic acid receptor agonist; induces differentiation.', category_id:'4', image_url:null, price_min:30, price_max:115, created_at:'' },
  // ── PROTEASOME & UBIQUITIN ──────────────────────────────────────────────
  { id:'71', name:'MG-132', slug:'mg-132', catalog_number:'VD-PI-0001', cas_number:'133407-82-6', formula:'C26H41N3O5', molecular_weight:'475.62', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'Z-Leu-Leu-Leu-al', description:'Potent cell-permeable proteasome inhibitor; blocks ubiquitin-mediated protein degradation.', category_id:'4', image_url:null, price_min:55, price_max:210, created_at:'' },
  { id:'72', name:'Lactacystin', slug:'lactacystin', catalog_number:'VD-PI-0002', cas_number:'133343-34-7', formula:'C15H24N2O6S', molecular_weight:'348.43', purity:'HPLC-98%', appearance:'White powder', solubility:'Water', storage:'-20°C', synonyms:null, description:'Natural product proteasome inhibitor; irreversibly inhibits the 20S proteasome.', category_id:'4', image_url:null, price_min:90, price_max:350, created_at:'' },
  { id:'73', name:'Epoxomicin', slug:'epoxomicin', catalog_number:'VD-PI-0003', cas_number:'134381-21-8', formula:'C28H50N4O7', molecular_weight:'554.72', purity:'HPLC-97%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:null, description:'Highly selective proteasome inhibitor with epoxyketone pharmacophore.', category_id:'4', image_url:null, price_min:110, price_max:430, created_at:'' },
  // ── AUTOPHAGY ───────────────────────────────────────────────────────────
  { id:'74', name:'Chloroquine diphosphate', slug:'chloroquine-diphosphate', catalog_number:'VD-AU-0001', cas_number:'50-63-5', formula:'C18H26ClN3·2H3PO4', molecular_weight:'515.87', purity:'HPLC-99%', appearance:'White crystalline powder', solubility:'Water', storage:'RT', synonyms:null, description:'Lysosomotropic agent that inhibits autophagy by preventing autophagosome-lysosome fusion.', category_id:'2', image_url:null, price_min:25, price_max:95, created_at:'' },
  { id:'75', name:'Bafilomycin A1', slug:'bafilomycin-a1', catalog_number:'VD-AU-0002', cas_number:'88899-55-2', formula:'C35H58O9', molecular_weight:'622.82', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:null, description:'Specific inhibitor of vacuolar-type H+-ATPase; blocks autophagy and acidification.', category_id:'4', image_url:null, price_min:95, price_max:370, created_at:'' },
  { id:'76', name:'3-Methyladenine', slug:'3-methyladenine', catalog_number:'VD-AU-0003', cas_number:'5142-23-4', formula:'C6H7N5', molecular_weight:'149.15', purity:'HPLC-98%', appearance:'White solid', solubility:'Water (warm)', storage:'RT', synonyms:'3-MA', description:'PI3K inhibitor used as a classic autophagy inhibitor in research.', category_id:'4', image_url:null, price_min:30, price_max:115, created_at:'' },
  { id:'77', name:'Rapamycin (Temsirolimus)', slug:'temsirolimus', catalog_number:'VD-AU-0004', cas_number:'162635-04-3', formula:'C56H87NO16', molecular_weight:'1030.29', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'CCI-779; Torisel', description:'mTORC1 inhibitor; induces autophagy and approved for renal cell carcinoma.', category_id:'3', image_url:null, price_min:100, price_max:390, created_at:'' },
  // ── STEM CELL / DIFFERENTIATION ─────────────────────────────────────────
  { id:'78', name:'Purmorphamine', slug:'purmorphamine', catalog_number:'VD-SC-0001', cas_number:'483367-10-8', formula:'C28H30N4O', molecular_weight:'454.57', purity:'HPLC-98%', appearance:'Yellow solid', solubility:'DMSO', storage:'-20°C', synonyms:'SMO agonist', description:'Smoothened agonist that activates Hedgehog signaling; promotes osteogenesis and neural differentiation.', category_id:'4', image_url:null, price_min:80, price_max:310, created_at:'' },
  { id:'79', name:'Thiazovivin', slug:'thiazovivin', catalog_number:'VD-SC-0002', cas_number:'1226056-71-8', formula:'C17H16N4OS', molecular_weight:'340.40', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'ROCK inhibitor II', description:'Novel ROCK inhibitor that promotes iPSC survival during reprogramming.', category_id:'4', image_url:null, price_min:85, price_max:330, created_at:'' },
  { id:'80', name:'IDE1', slug:'ide1', catalog_number:'VD-SC-0003', cas_number:'1130412-43-9', formula:'C13H11N3O3S', molecular_weight:'289.31', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'TGF-β inducer', description:'Small molecule that induces definitive endoderm differentiation from ESCs/iPSCs.', category_id:'4', image_url:null, price_min:90, price_max:350, created_at:'' },
  { id:'81', name:'RepSox', slug:'repsox', catalog_number:'VD-SC-0004', cas_number:'1129514-64-2', formula:'C16H13N3O', molecular_weight:'267.30', purity:'HPLC-98%', appearance:'Off-white solid', solubility:'DMSO', storage:'-20°C', synonyms:'E-616452; ALK5 inhibitor II', description:'ALK5/TGF-βRI inhibitor; used in somatic cell reprogramming to iPSCs.', category_id:'4', image_url:null, price_min:85, price_max:330, created_at:'' },
  // ── WNT SIGNALING ───────────────────────────────────────────────────────
  { id:'82', name:'XAV939', slug:'xav939', catalog_number:'VD-WN-0001', cas_number:'284028-89-3', formula:'C14H11F3N2O2S', molecular_weight:'328.31', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'Tankyrase inhibitor', description:'Tankyrase 1/2 inhibitor that suppresses Wnt/β-catenin signaling.', category_id:'4', image_url:null, price_min:70, price_max:270, created_at:'' },
  { id:'83', name:'IWR-1', slug:'iwr-1', catalog_number:'VD-WN-0002', cas_number:'1127442-82-3', formula:'C24H21N3O3', molecular_weight:'403.45', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'Wnt inhibitor', description:'Wnt pathway inhibitor that promotes Axin stabilization and β-catenin degradation.', category_id:'4', image_url:null, price_min:75, price_max:290, created_at:'' },
  { id:'84', name:'Wnt-C59', slug:'wnt-c59', catalog_number:'VD-WN-0003', cas_number:'1243243-89-1', formula:'C29H23N3O2', molecular_weight:'461.51', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'Porcupine inhibitor', description:'Potent Porcupine inhibitor that blocks Wnt ligand secretion.', category_id:'4', image_url:null, price_min:85, price_max:330, created_at:'' },
  { id:'85', name:'CHIR98014', slug:'chir98014', catalog_number:'VD-WN-0004', cas_number:'252935-94-7', formula:'C21H22Cl2N8O', molecular_weight:'493.36', purity:'HPLC-98%', appearance:'Yellow solid', solubility:'DMSO', storage:'-20°C', synonyms:'GSK-3 inhibitor', description:'Potent GSK-3α/β inhibitor that activates Wnt/β-catenin signaling.', category_id:'4', image_url:null, price_min:80, price_max:310, created_at:'' },
  // ── NOTCH SIGNALING ─────────────────────────────────────────────────────
  { id:'86', name:'DAPT', slug:'dapt', catalog_number:'VD-NO-0001', cas_number:'208255-80-5', formula:'C23H26F2N2O4', molecular_weight:'452.46', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'γ-secretase inhibitor IX', description:'γ-Secretase inhibitor that blocks Notch signaling; used in neural differentiation.', category_id:'4', image_url:null, price_min:60, price_max:230, created_at:'' },
  { id:'87', name:'LY411575', slug:'ly411575', catalog_number:'VD-NO-0002', cas_number:'209984-56-5', formula:'C25H22FN3O4', molecular_weight:'463.46', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'γ-secretase inhibitor', description:'Potent γ-secretase inhibitor; blocks Notch and amyloid precursor protein processing.', category_id:'4', image_url:null, price_min:75, price_max:290, created_at:'' },
  // ── METABOLISM / MITOCHONDRIA ────────────────────────────────────────────
  { id:'88', name:'AICAR', slug:'aicar', catalog_number:'VD-ME-0001', cas_number:'2627-69-2', formula:'C9H14N4O8P', molecular_weight:'338.21', purity:'HPLC-98%', appearance:'White solid', solubility:'Water', storage:'-20°C', synonyms:'Acadesine; AICA riboside', description:'AMPK activator; mimics AMP to activate AMP-activated protein kinase.', category_id:'4', image_url:null, price_min:55, price_max:210, created_at:'' },
  { id:'89', name:'Metformin HCl', slug:'metformin-hcl', catalog_number:'VD-ME-0002', cas_number:'1115-70-4', formula:'C4H11N5·HCl', molecular_weight:'165.62', purity:'HPLC-99%', appearance:'White crystalline solid', solubility:'Water', storage:'RT', synonyms:'Glucophage', description:'Biguanide AMPK activator; inhibits mitochondrial complex I; antidiabetic drug.', category_id:'4', image_url:null, price_min:20, price_max:75, created_at:'' },
  { id:'90', name:'Oligomycin A', slug:'oligomycin-a', catalog_number:'VD-ME-0003', cas_number:'579-13-5', formula:'C45H74O11', molecular_weight:'791.06', purity:'HPLC-95%', appearance:'White powder', solubility:'Ethanol', storage:'-20°C', synonyms:null, description:'ATP synthase inhibitor; blocks mitochondrial oxidative phosphorylation.', category_id:'4', image_url:null, price_min:80, price_max:310, created_at:'' },
  { id:'91', name:'Rotenone', slug:'rotenone', catalog_number:'VD-ME-0004', cas_number:'83-79-4', formula:'C23H22O6', molecular_weight:'394.42', purity:'HPLC-98%', appearance:'White solid', solubility:'Acetone', storage:'RT', synonyms:null, description:'Mitochondrial complex I inhibitor; used as Parkinson disease model compound.', category_id:'4', image_url:null, price_min:30, price_max:115, created_at:'' },
  { id:'92', name:'Antimycin A', slug:'antimycin-a', catalog_number:'VD-ME-0005', cas_number:'1397-94-0', formula:'C28H40N2O9', molecular_weight:'548.62', purity:'HPLC-95%', appearance:'Yellow solid', solubility:'Ethanol', storage:'-20°C', synonyms:null, description:'Mitochondrial complex III inhibitor; induces ROS production.', category_id:'4', image_url:null, price_min:45, price_max:175, created_at:'' },
  { id:'93', name:'FCCP', slug:'fccp', catalog_number:'VD-ME-0006', cas_number:'370-86-5', formula:'C10H5F3N2O', molecular_weight:'254.16', purity:'HPLC-98%', appearance:'Yellow solid', solubility:'DMSO', storage:'-20°C', synonyms:'Carbonyl cyanide-4-(trifluoromethoxy)phenylhydrazone', description:'Proton ionophore that uncouples mitochondrial oxidative phosphorylation.', category_id:'4', image_url:null, price_min:40, price_max:155, created_at:'' },
  // ── INFLAMMATION / NF-κB ────────────────────────────────────────────────
  { id:'94', name:'Bay 11-7082', slug:'bay-11-7082', catalog_number:'VD-NF-0001', cas_number:'19542-67-7', formula:'C10H9NO2S', molecular_weight:'207.25', purity:'HPLC-98%', appearance:'Yellow solid', solubility:'DMSO', storage:'-20°C', synonyms:'IKK inhibitor', description:'Irreversible inhibitor of IκBα phosphorylation; blocks NF-κB activation.', category_id:'4', image_url:null, price_min:50, price_max:190, created_at:'' },
  { id:'95', name:'Parthenolide', slug:'parthenolide', catalog_number:'VD-NF-0002', cas_number:'20554-84-1', formula:'C15H20O3', molecular_weight:'248.32', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:null, description:'Sesquiterpene lactone NF-κB inhibitor; anti-inflammatory and anticancer.', category_id:'4', image_url:null, price_min:55, price_max:210, created_at:'' },
  { id:'96', name:'JSH-23', slug:'jsh-23', catalog_number:'VD-NF-0003', cas_number:'749886-87-1', formula:'C16H19N3', molecular_weight:'253.35', purity:'HPLC-98%', appearance:'Yellow solid', solubility:'DMSO', storage:'-20°C', synonyms:'NF-κB nuclear translocation inhibitor', description:'Inhibits NF-κB transcriptional activity without affecting IκBα degradation.', category_id:'4', image_url:null, price_min:65, price_max:250, created_at:'' },
  { id:'97', name:'Celecoxib', slug:'celecoxib', catalog_number:'VD-NF-0004', cas_number:'169590-42-5', formula:'C17H14F3N3O2S', molecular_weight:'381.37', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'RT', synonyms:'Celebrex; COX-2 inhibitor', description:'Selective COX-2 inhibitor; NSAID with anticancer properties.', category_id:'4', image_url:null, price_min:35, price_max:135, created_at:'' },
  { id:'98', name:'Indomethacin', slug:'indomethacin', catalog_number:'VD-NF-0005', cas_number:'53-86-1', formula:'C19H16ClNO4', molecular_weight:'357.79', purity:'HPLC-99%', appearance:'White to pale yellow powder', solubility:'DMSO', storage:'RT', synonyms:null, description:'Non-selective COX-1/COX-2 inhibitor; anti-inflammatory NSAID.', category_id:'4', image_url:null, price_min:25, price_max:95, created_at:'' },
  // ── OXIDATIVE STRESS ────────────────────────────────────────────────────
  { id:'99', name:'N-Acetyl-L-cysteine', slug:'n-acetyl-l-cysteine', catalog_number:'VD-OS-0001', cas_number:'616-91-1', formula:'C5H9NO3S', molecular_weight:'163.19', purity:'HPLC-99%', appearance:'White crystalline powder', solubility:'Water', storage:'RT', synonyms:'NAC', description:'ROS scavenger and GSH precursor; widely used antioxidant in cell biology.', category_id:'4', image_url:null, price_min:20, price_max:75, created_at:'' },
  { id:'100', name:'Tert-butyl hydroperoxide', slug:'tert-butyl-hydroperoxide', catalog_number:'VD-OS-0002', cas_number:'75-91-2', formula:'C4H10O2', molecular_weight:'90.12', purity:'70% in water', appearance:'Colorless liquid', solubility:'Water', storage:'RT', synonyms:'tBHP; TBHP', description:'Organic peroxide used to induce oxidative stress in cell culture models.', category_id:'11', image_url:null, price_min:25, price_max:95, created_at:'' },
  { id:'101', name:'Menadione', slug:'menadione', catalog_number:'VD-OS-0003', cas_number:'58-27-5', formula:'C11H8O2', molecular_weight:'172.18', purity:'HPLC-98%', appearance:'Yellow solid', solubility:'Ethanol', storage:'RT', synonyms:'Vitamin K3; 2-Methylnaphthoquinone', description:'Generates superoxide radicals; used as oxidative stress inducer.', category_id:'11', image_url:null, price_min:25, price_max:95, created_at:'' },
  { id:'102', name:'Ebselen', slug:'ebselen', catalog_number:'VD-OS-0004', cas_number:'60940-34-3', formula:'C13H9NOSe', molecular_weight:'274.18', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'RT', synonyms:'PZ 51', description:'Glutathione peroxidase mimic; potent antioxidant and neuroprotective agent.', category_id:'4', image_url:null, price_min:55, price_max:210, created_at:'' },
  // ── CYTOSKELETAL ────────────────────────────────────────────────────────
  { id:'103', name:'Cytochalasin D', slug:'cytochalasin-d', catalog_number:'VD-CY-0001', cas_number:'22144-77-0', formula:'C30H37NO6', molecular_weight:'507.62', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:null, description:'Actin polymerization inhibitor; disrupts actin filament formation.', category_id:'4', image_url:null, price_min:65, price_max:250, created_at:'' },
  { id:'104', name:'Nocodazole', slug:'nocodazole', catalog_number:'VD-CY-0002', cas_number:'31430-18-9', formula:'C14H11N3O3S', molecular_weight:'301.32', purity:'HPLC-98%', appearance:'Yellow solid', solubility:'DMSO', storage:'-20°C', synonyms:null, description:'Reversible microtubule depolymerizer; used for cell cycle synchronization at G2/M.', category_id:'4', image_url:null, price_min:40, price_max:155, created_at:'' },
  { id:'105', name:'Blebbistatin', slug:'blebbistatin', catalog_number:'VD-CY-0003', cas_number:'674289-55-5', formula:'C18H16N2O2', molecular_weight:'292.34', purity:'HPLC-98%', appearance:'Yellow solid', solubility:'DMSO', storage:'-20°C', synonyms:'Myosin II inhibitor', description:'Selective non-muscle myosin II ATPase inhibitor; used in cell migration studies.', category_id:'4', image_url:null, price_min:70, price_max:270, created_at:'' },
  { id:'106', name:'Jasplakinolide', slug:'jasplakinolide', catalog_number:'VD-CY-0004', cas_number:'102396-24-7', formula:'C36H42BrN3O6', molecular_weight:'710.65', purity:'HPLC-95%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:null, description:'Actin stabilizer and polymerizer; cell-permeable macrolide.', category_id:'4', image_url:null, price_min:120, price_max:470, created_at:'' },
  // ── NUCLEAR RECEPTORS / HORMONES ────────────────────────────────────────
  { id:'107', name:'Dexamethasone', slug:'dexamethasone', catalog_number:'VD-HR-0001', cas_number:'50-02-2', formula:'C22H29FO5', molecular_weight:'392.46', purity:'HPLC-98%', appearance:'White crystalline powder', solubility:'Ethanol', storage:'RT', synonyms:null, description:'Synthetic glucocorticoid; induces adipogenesis; anti-inflammatory.', category_id:'4', image_url:null, price_min:25, price_max:95, created_at:'' },
  { id:'108', name:'17β-Estradiol', slug:'17beta-estradiol', catalog_number:'VD-HR-0002', cas_number:'50-28-2', formula:'C18H24O2', molecular_weight:'272.38', purity:'HPLC-98%', appearance:'White crystalline powder', solubility:'Ethanol', storage:'-20°C', synonyms:'E2; Oestradiol', description:'Primary female sex hormone; ERα/ERβ agonist; used in hormone research.', category_id:'4', image_url:null, price_min:30, price_max:115, created_at:'' },
  { id:'109', name:'Tamoxifen', slug:'tamoxifen', catalog_number:'VD-HR-0003', cas_number:'10540-29-1', formula:'C26H29NO', molecular_weight:'371.51', purity:'HPLC-98%', appearance:'White solid', solubility:'Ethanol', storage:'RT', synonyms:'Z-Tamoxifen', description:'Selective estrogen receptor modulator (SERM); widely used breast cancer research tool.', category_id:'3', image_url:null, price_min:30, price_max:115, created_at:'' },
  { id:'110', name:'Testosterone', slug:'testosterone', catalog_number:'VD-HR-0004', cas_number:'58-22-0', formula:'C19H28O2', molecular_weight:'288.42', purity:'HPLC-98%', appearance:'White crystalline powder', solubility:'Ethanol', storage:'RT', synonyms:null, description:'Primary androgen; androgen receptor agonist; used in reproductive biology research.', category_id:'4', image_url:null, price_min:30, price_max:115, created_at:'' },
  { id:'111', name:'Flutamide', slug:'flutamide', catalog_number:'VD-HR-0005', cas_number:'13311-84-7', formula:'C11H11F3N2O3', molecular_weight:'276.21', purity:'HPLC-98%', appearance:'Yellow solid', solubility:'DMSO', storage:'RT', synonyms:'Eulexin', description:'Non-steroidal androgen receptor antagonist; prostate cancer research.', category_id:'3', image_url:null, price_min:30, price_max:115, created_at:'' },
  // ── KINASE INHIBITORS (ADDITIONAL) ──────────────────────────────────────
  { id:'112', name:'Sorafenib', slug:'sorafenib', catalog_number:'VD-KI-0001', cas_number:'284461-73-0', formula:'C21H16ClF3N4O3', molecular_weight:'464.82', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'Bay 43-9006; Nexavar', description:'Multi-kinase inhibitor targeting RAF, VEGFR, PDGFR; hepatocellular carcinoma treatment.', category_id:'3', image_url:null, price_min:70, price_max:270, created_at:'' },
  { id:'113', name:'Sunitinib malate', slug:'sunitinib-malate', catalog_number:'VD-KI-0002', cas_number:'341031-54-7', formula:'C22H27FN4O2·C4H6O5', molecular_weight:'532.56', purity:'HPLC-98%', appearance:'Yellow-orange solid', solubility:'DMSO', storage:'-20°C', synonyms:'SU11248; Sutent', description:'Multi-targeted receptor tyrosine kinase inhibitor; antiangiogenic and antitumor.', category_id:'3', image_url:null, price_min:70, price_max:270, created_at:'' },
  { id:'114', name:'Lapatinib', slug:'lapatinib', catalog_number:'VD-KI-0003', cas_number:'231277-92-2', formula:'C29H26ClFN4O4S', molecular_weight:'581.06', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'GW-572016; Tykerb', description:'Dual EGFR/HER2 tyrosine kinase inhibitor; breast cancer research.', category_id:'3', image_url:null, price_min:75, price_max:290, created_at:'' },
  { id:'115', name:'Vemurafenib', slug:'vemurafenib', catalog_number:'VD-KI-0004', cas_number:'918504-65-1', formula:'C23H18ClF2N3O3S', molecular_weight:'489.92', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'PLX4032; Zelboraf', description:'BRAF V600E selective inhibitor; approved for metastatic melanoma.', category_id:'3', image_url:null, price_min:85, price_max:330, created_at:'' },
  { id:'116', name:'Trametinib', slug:'trametinib', catalog_number:'VD-KI-0005', cas_number:'871700-17-3', formula:'C26H23FIN5O4', molecular_weight:'615.39', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'GSK1120212; Mekinist', description:'Allosteric MEK1/MEK2 inhibitor; approved for melanoma with BRAF V600 mutation.', category_id:'3', image_url:null, price_min:90, price_max:350, created_at:'' },
  { id:'117', name:'Palbociclib', slug:'palbociclib', catalog_number:'VD-KI-0006', cas_number:'571190-30-2', formula:'C24H29N7O2', molecular_weight:'447.54', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'PD-0332991; Ibrance', description:'Selective CDK4/6 inhibitor; approved for HR+/HER2- breast cancer.', category_id:'3', image_url:null, price_min:90, price_max:350, created_at:'' },
  { id:'118', name:'Ibrutinib', slug:'ibrutinib', catalog_number:'VD-KI-0007', cas_number:'936563-96-1', formula:'C25H24N6O2', molecular_weight:'440.50', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'PCI-32765; Imbruvica', description:'Irreversible BTK inhibitor; approved for CLL and mantle cell lymphoma.', category_id:'3', image_url:null, price_min:90, price_max:350, created_at:'' },
  { id:'119', name:'Idelalisib', slug:'idelalisib', catalog_number:'VD-KI-0008', cas_number:'870281-82-6', formula:'C22H18FN7O', molecular_weight:'415.42', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'GS-1101; Zydelig', description:'Selective PI3Kδ inhibitor; approved for CLL and follicular lymphoma.', category_id:'3', image_url:null, price_min:85, price_max:330, created_at:'' },
  // ── ANGIOGENESIS ────────────────────────────────────────────────────────
  { id:'120', name:'Bevacizumab (biosimilar reference)', slug:'suramin', catalog_number:'VD-AN-0001', cas_number:'129-46-4', formula:'C51H40N6O23S6·6Na', molecular_weight:'1429.17', purity:'HPLC-98%', appearance:'White powder', solubility:'Water', storage:'RT', synonyms:'Suramin sodium', description:'Polysulfonated naphthylurea; VEGF, PDGF, FGF inhibitor; antiangiogenic.', category_id:'3', image_url:null, price_min:40, price_max:155, created_at:'' },
  { id:'121', name:'SU1498', slug:'su1498', catalog_number:'VD-AN-0002', cas_number:'192185-72-1', formula:'C20H17N3O3', molecular_weight:'351.37', purity:'HPLC-98%', appearance:'Red solid', solubility:'DMSO', storage:'-20°C', synonyms:'VEGFR2 inhibitor', description:'Selective VEGFR-2 (KDR/Flk-1) tyrosine kinase inhibitor; antiangiogenic.', category_id:'3', image_url:null, price_min:75, price_max:290, created_at:'' },
  // ── AMINO ACIDS ADDITIONAL ──────────────────────────────────────────────
  { id:'122', name:'Fmoc-Gly-OH', slug:'fmoc-gly-oh', catalog_number:'VD-UAA-0187', cas_number:'29022-11-5', formula:'C17H15NO4', molecular_weight:'297.31', purity:'HPLC-99%', appearance:'White powder', solubility:'DMF', storage:'RT', synonyms:null, description:'Fmoc-protected glycine for solid-phase peptide synthesis.', category_id:'9', image_url:null, price_min:30, price_max:115, created_at:'' },
  { id:'123', name:'Fmoc-Ala-OH', slug:'fmoc-ala-oh', catalog_number:'VD-UAA-0130', cas_number:'35661-39-3', formula:'C18H17NO4', molecular_weight:'311.34', purity:'HPLC-99%', appearance:'White powder', solubility:'DMF', storage:'RT', synonyms:null, description:'Fmoc-protected alanine for automated SPPS.', category_id:'9', image_url:null, price_min:30, price_max:115, created_at:'' },
  { id:'124', name:'Boc-Phe-OH', slug:'boc-phe-oh', catalog_number:'VD-UAA-0070', cas_number:'13734-34-4', formula:'C14H19NO4', molecular_weight:'265.31', purity:'HPLC-99%', appearance:'White crystalline solid', solubility:'DCM', storage:'RT', synonyms:null, description:'Boc-protected phenylalanine for peptide synthesis.', category_id:'9', image_url:null, price_min:35, price_max:135, created_at:'' },
  { id:'125', name:'H-Pro-OH', slug:'h-pro-oh', catalog_number:'VD-UAA-0306', cas_number:'147-85-3', formula:'C5H9NO2', molecular_weight:'115.13', purity:'HPLC-99%', appearance:'White crystalline powder', solubility:'Water', storage:'RT', synonyms:'L-Proline', description:'Cyclic amino acid essential for collagen structure; used in peptide synthesis.', category_id:'9', image_url:null, price_min:20, price_max:75, created_at:'' },
  { id:'126', name:'H-Orn(Boc)-OH', slug:'h-orn-boc-oh', catalog_number:'VD-UAA-0291', cas_number:'2200-39-7', formula:'C10H20N2O4', molecular_weight:'232.28', purity:'HPLC-98%', appearance:'White solid', solubility:'Water', storage:'RT', synonyms:null, description:'Boc-protected ornithine; non-standard amino acid for peptidomimetics.', category_id:'9', image_url:null, price_min:55, price_max:210, created_at:'' },
  // ── FLUORESCENT PROBES / DYES ────────────────────────────────────────────
  { id:'127', name:'Hoechst 33342', slug:'hoechst-33342', catalog_number:'VD-DY-0001', cas_number:'23491-45-4', formula:'C27H28Cl2N6O', molecular_weight:'561.50', purity:'HPLC-95%', appearance:'Light yellow powder', solubility:'Water', storage:'RT', synonyms:'Bisbenzimide H 33342', description:'Cell-permeable DNA-binding fluorescent stain for nuclear visualization.', category_id:'11', image_url:null, price_min:45, price_max:175, created_at:'' },
  { id:'128', name:'Propidium iodide', slug:'propidium-iodide', catalog_number:'VD-DY-0002', cas_number:'25535-16-4', formula:'C27H34I2N4', molecular_weight:'668.40', purity:'HPLC-95%', appearance:'Red-orange powder', solubility:'Water', storage:'RT', synonyms:'PI', description:'Cell-impermeable DNA intercalating dye; used for dead cell discrimination in flow cytometry.', category_id:'11', image_url:null, price_min:30, price_max:115, created_at:'' },
  { id:'129', name:'DAPI', slug:'dapi', catalog_number:'VD-DY-0003', cas_number:'28718-90-3', formula:'C16H15N5·2HCl', molecular_weight:'350.25', purity:'HPLC-95%', appearance:'White to light yellow powder', solubility:'Water', storage:'-20°C', synonyms:"4',6-Diamidino-2-phenylindole", description:'Fluorescent DNA stain for nuclear counterstaining in fluorescence microscopy.', category_id:'11', image_url:null, price_min:35, price_max:135, created_at:'' },
  // ── ANTIFUNGALS ─────────────────────────────────────────────────────────
  { id:'130', name:'Amphotericin B', slug:'amphotericin-b', catalog_number:'VD-AF-0001', cas_number:'1397-89-3', formula:'C47H73NO17', molecular_weight:'924.08', purity:'HPLC-95%', appearance:'Yellow powder', solubility:'DMSO', storage:'-20°C', synonyms:'Fungizone', description:'Polyene antifungal antibiotic; binds ergosterol in fungal membranes.', category_id:'5', image_url:null, price_min:40, price_max:155, created_at:'' },
  { id:'131', name:'Fluconazole', slug:'fluconazole', catalog_number:'VD-AF-0002', cas_number:'86386-73-4', formula:'C13H12F2N6O', molecular_weight:'306.27', purity:'HPLC-98%', appearance:'White crystalline solid', solubility:'DMSO', storage:'RT', synonyms:'Diflucan', description:'Triazole antifungal; CYP51 inhibitor blocking ergosterol biosynthesis.', category_id:'5', image_url:null, price_min:30, price_max:115, created_at:'' },
  { id:'132', name:'Caspofungin acetate', slug:'caspofungin-acetate', catalog_number:'VD-AF-0003', cas_number:'179463-17-3', formula:'C52H88N10O15·CH3CO2H', molecular_weight:'1213.42', purity:'HPLC-95%', appearance:'White powder', solubility:'Water', storage:'-20°C', synonyms:'MK-0991; Cancidas', description:'Echinocandin antifungal; inhibits β-1,3-D-glucan synthase in fungal cell wall.', category_id:'5', image_url:null, price_min:110, price_max:430, created_at:'' },
  // ── ANTIPARASITIC ───────────────────────────────────────────────────────
  { id:'133', name:'Ivermectin', slug:'ivermectin', catalog_number:'VD-AP-0001', cas_number:'70288-86-7', formula:'C48H74O14', molecular_weight:'875.10', purity:'HPLC-98%', appearance:'White powder', solubility:'DMSO', storage:'-20°C', synonyms:'Mectizan', description:'Broad-spectrum antiparasitic; glutamate-gated chloride channel activator.', category_id:'1', image_url:null, price_min:45, price_max:175, created_at:'' },
  { id:'134', name:'Chloroquine phosphate', slug:'chloroquine-phosphate', catalog_number:'VD-AP-0002', cas_number:'50-63-5', formula:'C18H26ClN3·2H3PO4', molecular_weight:'515.87', purity:'HPLC-99%', appearance:'White crystalline powder', solubility:'Water', storage:'RT', synonyms:null, description:'4-Aminoquinoline antimalarial; also used as autophagy inhibitor.', category_id:'1', image_url:null, price_min:25, price_max:95, created_at:'' },
  { id:'135', name:'Artemisinin', slug:'artemisinin', catalog_number:'VD-AP-0003', cas_number:'63968-64-9', formula:'C15H22O5', molecular_weight:'282.33', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'RT', synonyms:'Qinghaosu', description:'Sesquiterpene endoperoxide antimalarial from Artemisia annua; Nobel Prize compound.', category_id:'1', image_url:null, price_min:40, price_max:155, created_at:'' },
  // ── CELL SIGNALING MISC ─────────────────────────────────────────────────
  { id:'136', name:'SP600125', slug:'sp600125', catalog_number:'VD-SI-0001', cas_number:'129-56-6', formula:'C14H8N2O', molecular_weight:'220.23', purity:'HPLC-98%', appearance:'Yellow solid', solubility:'DMSO', storage:'-20°C', synonyms:'JNK inhibitor II', description:'Reversible ATP-competitive JNK1/2/3 inhibitor; used in stress signaling studies.', category_id:'4', image_url:null, price_min:55, price_max:210, created_at:'' },
  { id:'137', name:'U0126', slug:'u0126', catalog_number:'VD-SI-0002', cas_number:'109511-58-2', formula:'C18H16N4S2', molecular_weight:'380.47', purity:'HPLC-98%', appearance:'Yellow solid', solubility:'DMSO', storage:'-20°C', synonyms:'MEK1/2 inhibitor', description:'Non-competitive MEK1/2 inhibitor; more potent than PD98059.', category_id:'4', image_url:null, price_min:65, price_max:250, created_at:'' },
  { id:'138', name:'SB216763', slug:'sb216763', catalog_number:'VD-SI-0003', cas_number:'280744-09-4', formula:'C20H14ClN3O3', molecular_weight:'383.80', purity:'HPLC-98%', appearance:'Yellow solid', solubility:'DMSO', storage:'-20°C', synonyms:'GSK-3 inhibitor', description:'Selective GSK-3α/β inhibitor; promotes Wnt target gene expression.', category_id:'4', image_url:null, price_min:70, price_max:270, created_at:'' },
  { id:'139', name:'H-89 dihydrochloride', slug:'h-89-dihydrochloride', catalog_number:'VD-SI-0004', cas_number:'130964-39-5', formula:'C20H22BrN3O2S·2HCl', molecular_weight:'507.29', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'PKA inhibitor', description:'Potent and selective protein kinase A (PKA/cAMP-dependent kinase) inhibitor.', category_id:'4', image_url:null, price_min:65, price_max:250, created_at:'' },
  { id:'140', name:'Go6983', slug:'go6983', catalog_number:'VD-SI-0005', cas_number:'133053-19-7', formula:'C22H18N4O2', molecular_weight:'374.41', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'Pan-PKC inhibitor', description:'Broad-spectrum PKCα, β, γ, δ, ζ inhibitor; used in T cell signaling research.', category_id:'4', image_url:null, price_min:70, price_max:270, created_at:'' },
  // ── IMMUNOLOGY ──────────────────────────────────────────────────────────
  { id:'141', name:'Cyclosporin A', slug:'cyclosporin-a', catalog_number:'VD-IM-0001', cas_number:'59865-13-3', formula:'C62H111N11O12', molecular_weight:'1202.61', purity:'HPLC-98%', appearance:'White powder', solubility:'Ethanol', storage:'-20°C', synonyms:'Cyclosporine; CsA', description:'Calcineurin inhibitor; suppresses T-cell activation by blocking NFAT nuclear translocation.', category_id:'4', image_url:null, price_min:55, price_max:210, created_at:'' },
  { id:'142', name:'FK506', slug:'fk506', catalog_number:'VD-IM-0002', cas_number:'104987-11-3', formula:'C44H69NO12', molecular_weight:'804.02', purity:'HPLC-98%', appearance:'White powder', solubility:'DMSO', storage:'-20°C', synonyms:'Tacrolimus; Fujimycin', description:'FKBP12-binding macrolide; potent calcineurin inhibitor used in transplant immunosuppression.', category_id:'4', image_url:null, price_min:90, price_max:350, created_at:'' },
  { id:'143', name:'Mycophenolic acid', slug:'mycophenolic-acid', catalog_number:'VD-IM-0003', cas_number:'24280-93-1', formula:'C17H20O6', molecular_weight:'320.34', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'RT', synonyms:'MPA', description:'Inosine monophosphate dehydrogenase (IMPDH) inhibitor; suppresses lymphocyte proliferation.', category_id:'4', image_url:null, price_min:35, price_max:135, created_at:'' },
  { id:'144', name:'Leflunomide', slug:'leflunomide', catalog_number:'VD-IM-0004', cas_number:'75706-12-6', formula:'C12H9F3N2O2', molecular_weight:'270.21', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'RT', synonyms:'Arava; SU101', description:'DHODH inhibitor; blocks pyrimidine synthesis in activated lymphocytes.', category_id:'4', image_url:null, price_min:35, price_max:135, created_at:'' },
  { id:'145', name:'Tofacitinib citrate', slug:'tofacitinib-citrate', catalog_number:'VD-IM-0005', cas_number:'540737-29-9', formula:'C16H20N6O·C6H8O7', molecular_weight:'504.49', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'CP-690550; Xeljanz', description:'Pan-JAK inhibitor (JAK1/3 selective); approved for rheumatoid arthritis.', category_id:'4', image_url:null, price_min:80, price_max:310, created_at:'' },
  { id:'146', name:'Baricitinib', slug:'baricitinib', catalog_number:'VD-IM-0006', cas_number:'1187594-09-7', formula:'C16H17N7O2S', molecular_weight:'371.42', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'LY3009104; Olumiant', description:'JAK1/JAK2 selective inhibitor; approved for rheumatoid arthritis and alopecia areata.', category_id:'4', image_url:null, price_min:85, price_max:330, created_at:'' },
  // ── NEUROSCIENCE ────────────────────────────────────────────────────────
  { id:'147', name:'Memantine HCl', slug:'memantine-hcl', catalog_number:'VD-NS-0001', cas_number:'41100-52-1', formula:'C12H21N·HCl', molecular_weight:'215.76', purity:'HPLC-99%', appearance:'White crystalline solid', solubility:'Water', storage:'RT', synonyms:'Namenda; Axura', description:'NMDA receptor antagonist; approved for moderate-to-severe Alzheimer disease.', category_id:'7', image_url:null, price_min:30, price_max:115, created_at:'' },
  { id:'148', name:'Ketamine HCl', slug:'ketamine-hcl', catalog_number:'VD-NS-0002', cas_number:'1867-66-9', formula:'C13H16ClNO·HCl', molecular_weight:'274.19', purity:'HPLC-98%', appearance:'White crystalline powder', solubility:'Water', storage:'RT', synonyms:'CI-581', description:'NMDA receptor antagonist; dissociative anesthetic and rapid-acting antidepressant research tool.', category_id:'7', image_url:null, price_min:35, price_max:135, created_at:'' },
  { id:'149', name:'MK-801 maleate', slug:'mk-801-maleate', catalog_number:'VD-NS-0003', cas_number:'77086-22-7', formula:'C16H15N·C4H4O4', molecular_weight:'337.37', purity:'HPLC-98%', appearance:'White solid', solubility:'Water', storage:'-20°C', synonyms:'Dizocilpine; (+)-MK801', description:'Potent non-competitive NMDA receptor antagonist; used in neuroprotection studies.', category_id:'7', image_url:null, price_min:55, price_max:210, created_at:'' },
  { id:'150', name:'6-OHDA hydrobromide', slug:'6-ohda-hydrobromide', catalog_number:'VD-NS-0004', cas_number:'636-00-0', formula:'C8H11NO3·HBr', molecular_weight:'250.09', purity:'HPLC-97%', appearance:'White to light brown solid', solubility:'Water (0.1% ascorbic acid)', storage:'-80°C', synonyms:'6-Hydroxydopamine', description:'Catecholaminergic neurotoxin; used to create Parkinson disease models in rodents.', category_id:'7', image_url:null, price_min:45, price_max:175, created_at:'' },
  { id:'151', name:'MPTP HCl', slug:'mptp-hcl', catalog_number:'VD-NS-0005', cas_number:'23007-85-4', formula:'C12H15N·HCl', molecular_weight:'209.72', purity:'HPLC-98%', appearance:'White solid', solubility:'Water', storage:'-20°C', synonyms:'1-Methyl-4-phenyl-1,2,3,6-tetrahydropyridine', description:'Neurotoxin selectively destroying dopaminergic neurons; Parkinson disease research.', category_id:'7', image_url:null, price_min:55, price_max:210, created_at:'' },
  { id:'152', name:'Kainic acid', slug:'kainic-acid', catalog_number:'VD-NS-0006', cas_number:'487-79-6', formula:'C10H15NO4', molecular_weight:'213.23', purity:'HPLC-98%', appearance:'White crystalline powder', solubility:'Water', storage:'-20°C', synonyms:'Kainate', description:'Glutamate receptor agonist (kainate subtype); used to model temporal lobe epilepsy.', category_id:'7', image_url:null, price_min:60, price_max:230, created_at:'' },
  { id:'153', name:'Gabapentin', slug:'gabapentin', catalog_number:'VD-NS-0007', cas_number:'60142-96-3', formula:'C9H17NO2', molecular_weight:'171.24', purity:'HPLC-99%', appearance:'White crystalline solid', solubility:'Water', storage:'RT', synonyms:'Neurontin; CI-945', description:'Voltage-gated calcium channel α2δ subunit ligand; anticonvulsant and analgesic.', category_id:'7', image_url:null, price_min:25, price_max:95, created_at:'' },
  // ── CARDIOLOGY ──────────────────────────────────────────────────────────
  { id:'154', name:'Digoxin', slug:'digoxin', catalog_number:'VD-CA-0001', cas_number:'20830-75-5', formula:'C41H64O14', molecular_weight:'780.94', purity:'HPLC-98%', appearance:'White crystalline powder', solubility:'Ethanol', storage:'RT', synonyms:'Lanoxin', description:'Cardiac glycoside; Na+/K+-ATPase inhibitor; positive inotrope.', category_id:'8', image_url:null, price_min:30, price_max:115, created_at:'' },
  { id:'155', name:'Nifedipine', slug:'nifedipine', catalog_number:'VD-CA-0002', cas_number:'21829-25-4', formula:'C17H18N2O6', molecular_weight:'346.34', purity:'HPLC-98%', appearance:'Yellow crystalline powder', solubility:'Acetone', storage:'RT (protect from light)', synonyms:'Adalat; Procardia', description:'Dihydropyridine L-type calcium channel blocker; vasodilator and antihypertensive.', category_id:'8', image_url:null, price_min:25, price_max:95, created_at:'' },
  { id:'156', name:'Verapamil HCl', slug:'verapamil-hcl', catalog_number:'VD-CA-0003', cas_number:'152-11-4', formula:'C27H38N2O4·HCl', molecular_weight:'491.06', purity:'HPLC-99%', appearance:'White crystalline powder', solubility:'Water', storage:'RT', synonyms:'Calan; Isoptin', description:'Phenylalkylamine calcium channel blocker; also P-glycoprotein inhibitor.', category_id:'8', image_url:null, price_min:25, price_max:95, created_at:'' },
  { id:'157', name:'Amiodarone HCl', slug:'amiodarone-hcl', catalog_number:'VD-CA-0004', cas_number:'19774-82-4', formula:'C25H29I2NO3·HCl', molecular_weight:'681.77', purity:'HPLC-98%', appearance:'White to off-white solid', solubility:'DMSO', storage:'RT', synonyms:'Cordarone', description:'Class III antiarrhythmic; potassium channel blocker; also inhibits Na+ and Ca2+ channels.', category_id:'8', image_url:null, price_min:35, price_max:135, created_at:'' },
  // ── LIPID / CHOLESTEROL ─────────────────────────────────────────────────
  { id:'158', name:'Lovastatin', slug:'lovastatin', catalog_number:'VD-LP-0001', cas_number:'75330-75-5', formula:'C24H36O5', molecular_weight:'404.54', purity:'HPLC-98%', appearance:'White crystalline solid', solubility:'DMSO', storage:'RT', synonyms:'Mevacor; Mevinolin', description:'HMG-CoA reductase inhibitor; reduces cholesterol biosynthesis.', category_id:'4', image_url:null, price_min:30, price_max:115, created_at:'' },
  { id:'159', name:'Simvastatin', slug:'simvastatin', catalog_number:'VD-LP-0002', cas_number:'79902-63-9', formula:'C25H38O5', molecular_weight:'418.57', purity:'HPLC-98%', appearance:'White crystalline powder', solubility:'DMSO', storage:'RT', synonyms:'Zocor', description:'Semisynthetic HMG-CoA reductase inhibitor; pleiotropic anticancer effects.', category_id:'4', image_url:null, price_min:30, price_max:115, created_at:'' },
  { id:'160', name:'U18666A', slug:'u18666a', catalog_number:'VD-LP-0003', cas_number:'3039-71-2', formula:'C27H45NO', molecular_weight:'411.65', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'NPC1 inhibitor', description:'Inhibits intracellular cholesterol transport; induces Niemann-Pick type C phenotype.', category_id:'4', image_url:null, price_min:65, price_max:250, created_at:'' },
  // ── CELL CYCLE ──────────────────────────────────────────────────────────
  { id:'161', name:'Aphidicolin', slug:'aphidicolin', catalog_number:'VD-CC-0001', cas_number:'38966-21-1', formula:'C20H34O4', molecular_weight:'338.48', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'NSC 234714', description:'DNA polymerase α/δ inhibitor; reversible G1/S cell cycle arrest agent.', category_id:'3', image_url:null, price_min:70, price_max:270, created_at:'' },
  { id:'162', name:'Mimosine', slug:'mimosine', catalog_number:'VD-CC-0002', cas_number:'500-44-7', formula:'C8H10N2O4', molecular_weight:'198.18', purity:'HPLC-98%', appearance:'White powder', solubility:'Water (alkaline)', storage:'RT', synonyms:'β-3-Hydroxy-4-pyridone amino acid', description:'Plant amino acid that blocks DNA replication; used for late G1 synchronization.', category_id:'3', image_url:null, price_min:35, price_max:135, created_at:'' },
  { id:'163', name:'Thymidine', slug:'thymidine', catalog_number:'VD-CC-0003', cas_number:'50-89-5', formula:'C10H14N2O5', molecular_weight:'242.23', purity:'HPLC-99%', appearance:'White crystalline powder', solubility:'Water', storage:'RT', synonyms:'dThd', description:'DNA precursor used for double thymidine block synchronization at G1/S boundary.', category_id:'3', image_url:null, price_min:20, price_max:75, created_at:'' },
  { id:'164', name:'RO-3306', slug:'ro-3306', catalog_number:'VD-CC-0004', cas_number:'872573-93-8', formula:'C20H20N4O3S', molecular_weight:'400.46', purity:'HPLC-98%', appearance:'Orange solid', solubility:'DMSO', storage:'-20°C', synonyms:'CDK1 inhibitor', description:'Selective ATP-competitive CDK1/cyclin B inhibitor; arrests cells at G2/M boundary.', category_id:'3', image_url:null, price_min:80, price_max:310, created_at:'' },
  // ── FERROPTOSIS ─────────────────────────────────────────────────────────
  { id:'165', name:'RSL3', slug:'rsl3', catalog_number:'VD-FP-0001', cas_number:'1219810-16-8', formula:'C23H20ClNO3', molecular_weight:'413.86', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'RAS-selective lethal 3; GPX4 inhibitor', description:'Potent GPX4 inhibitor that induces ferroptosis; used in cancer and cell death research.', category_id:'2', image_url:null, price_min:90, price_max:350, created_at:'' },
  { id:'166', name:'Erastin', slug:'erastin', catalog_number:'VD-FP-0002', cas_number:'571203-78-6', formula:'C30H31ClN4O4', molecular_weight:'571.04', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'System Xc- inhibitor', description:'Ferroptosis inducer; inhibits system Xc- cystine/glutamate antiporter.', category_id:'2', image_url:null, price_min:85, price_max:330, created_at:'' },
  { id:'167', name:'Ferrostatin-1', slug:'ferrostatin-1', catalog_number:'VD-FP-0003', cas_number:'347174-05-4', formula:'C13H18N2O2', molecular_weight:'234.30', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'Fer-1', description:'Lipophilic radical-trapping antioxidant; potent ferroptosis inhibitor.', category_id:'2', image_url:null, price_min:75, price_max:290, created_at:'' },
  { id:'168', name:'Liproxstatin-1', slug:'liproxstatin-1', catalog_number:'VD-FP-0004', cas_number:'950455-15-9', formula:'C19H21N3O2', molecular_weight:'323.39', purity:'HPLC-98%', appearance:'Yellow solid', solubility:'DMSO', storage:'-20°C', synonyms:'Lip-1', description:'Potent spiroquinoxalinamine ferroptosis inhibitor; more stable than Ferrostatin-1.', category_id:'2', image_url:null, price_min:85, price_max:330, created_at:'' },
  // ── NECROPTOSIS ─────────────────────────────────────────────────────────
  { id:'169', name:'Necrostatin-1', slug:'necrostatin-1', catalog_number:'VD-NP-0080', cas_number:'4311-88-0', formula:'C13H13N3OS', molecular_weight:'259.33', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'Nec-1; RIPK1 inhibitor', description:'First-in-class RIPK1 kinase inhibitor; blocks necroptosis and necroptotic signaling.', category_id:'2', image_url:null, price_min:65, price_max:250, created_at:'' },
  { id:'170', name:'GSK872', slug:'gsk872', catalog_number:'VD-NP-0081', cas_number:'1346527-98-7', formula:'C20H16N4O', molecular_weight:'332.37', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'RIPK3 inhibitor', description:'Selective RIPK3 kinase inhibitor; blocks necroptotic signaling downstream of RIPK1.', category_id:'2', image_url:null, price_min:85, price_max:330, created_at:'' },
  // ── PYROPTOSIS ──────────────────────────────────────────────────────────
  { id:'171', name:'Nigericin sodium salt', slug:'nigericin-sodium-salt', catalog_number:'VD-PY-0001', cas_number:'28643-80-3', formula:'C40H67O11·Na', molecular_weight:'747.96', purity:'HPLC-95%', appearance:'White solid', solubility:'Ethanol', storage:'-20°C', synonyms:'Polyetherin A', description:'K+/H+ ionophore; activates NLRP3 inflammasome; used to study pyroptosis.', category_id:'2', image_url:null, price_min:70, price_max:270, created_at:'' },
  { id:'172', name:'Disulfiram', slug:'disulfiram', catalog_number:'VD-PY-0002', cas_number:'97-77-8', formula:'C10H20N2S4', molecular_weight:'296.54', purity:'HPLC-98%', appearance:'White to pale yellow powder', solubility:'DMSO', storage:'RT', synonyms:'Antabuse; DSF', description:'ALDH inhibitor; repurposed anticancer drug that activates gasdermin D-mediated pyroptosis.', category_id:'3', image_url:null, price_min:25, price_max:95, created_at:'' },
  // ── SIRTUIN / NAD ────────────────────────────────────────────────────────
  { id:'173', name:'Resveratrol', slug:'resveratrol', catalog_number:'VD-SR-0001', cas_number:'501-36-0', formula:'C14H12O3', molecular_weight:'228.24', purity:'HPLC-99%', appearance:'White to off-white powder', solubility:'DMSO', storage:'-20°C', synonyms:'trans-Resveratrol; SRT501', description:'Natural polyphenol SIRT1 activator; pleiotropic effects on cancer, inflammation, metabolism.', category_id:'4', image_url:null, price_min:20, price_max:75, created_at:'' },
  { id:'174', name:'Nicotinamide', slug:'nicotinamide', catalog_number:'VD-SR-0002', cas_number:'98-92-0', formula:'C6H6N2O', molecular_weight:'122.12', purity:'HPLC-99%', appearance:'White crystalline powder', solubility:'Water', storage:'RT', synonyms:'Niacinamide; Vitamin B3', description:'NAD+ precursor; PARP and sirtuin modulator; epigenetic research tool.', category_id:'4', image_url:null, price_min:15, price_max:55, created_at:'' },
  { id:'175', name:'EX-527', slug:'ex-527', catalog_number:'VD-SR-0003', cas_number:'49843-98-3', formula:'C13H12ClN3O', molecular_weight:'261.71', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'Selisistat; SIRT1 inhibitor', description:'Potent selective SIRT1 deacetylase inhibitor; increases p53 acetylation.', category_id:'4', image_url:null, price_min:70, price_max:270, created_at:'' },
  // ── TELOMERE / TELOMERASE ────────────────────────────────────────────────
  { id:'176', name:'BIBR 1532', slug:'bibr-1532', catalog_number:'VD-TL-0001', cas_number:'321674-73-1', formula:'C21H16N2O3', molecular_weight:'348.37', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'Telomerase inhibitor', description:'Non-competitive selective telomerase inhibitor; induces telomere shortening and senescence.', category_id:'3', image_url:null, price_min:80, price_max:310, created_at:'' },
  // ── SENESCENCE ──────────────────────────────────────────────────────────
  { id:'177', name:'Navitoclax', slug:'navitoclax', catalog_number:'VD-SN-0001', cas_number:'1044570-70-8', formula:'C47H55ClF3N5O6S', molecular_weight:'974.49', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'ABT-263', description:'BCL-2/BCL-XL/BCL-W inhibitor; senolytic that clears senescent cells.', category_id:'3', image_url:null, price_min:95, price_max:370, created_at:'' },
  { id:'178', name:'Dasatinib', slug:'dasatinib', catalog_number:'VD-SN-0002', cas_number:'302962-49-8', formula:'C22H26ClN7O2S', molecular_weight:'488.01', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'BMS-354825; Sprycel', description:'BCR-ABL/Src kinase inhibitor; used with quercetin as senolytic combination.', category_id:'3', image_url:null, price_min:80, price_max:310, created_at:'' },
  { id:'179', name:'Quercetin', slug:'quercetin', catalog_number:'VD-SN-0003', cas_number:'117-39-5', formula:'C15H10O7', molecular_weight:'302.24', purity:'HPLC-98%', appearance:'Yellow powder', solubility:'DMSO', storage:'RT', synonyms:'Sophoretin; Meletin', description:'Flavonoid senolytic; inhibits PI3K/AKT survival pathways in senescent cells.', category_id:'4', image_url:null, price_min:20, price_max:75, created_at:'' },
  // ── FERROPTOSIS / IRON ──────────────────────────────────────────────────
  { id:'180', name:'Deferoxamine mesylate', slug:'deferoxamine-mesylate', catalog_number:'VD-IR-0001', cas_number:'138-14-7', formula:'C25H48N6O8·CH4O3S', molecular_weight:'656.79', purity:'HPLC-98%', appearance:'White powder', solubility:'Water', storage:'RT', synonyms:'DFO; Desferrioxamine B', description:'Iron chelator; inhibits ferroptosis; used in iron overload and ischemia research.', category_id:'4', image_url:null, price_min:30, price_max:115, created_at:'' },
  // ── GLYCOLYSIS / WARBURG ─────────────────────────────────────────────────
  { id:'181', name:'2-Deoxy-D-glucose', slug:'2-deoxy-d-glucose', catalog_number:'VD-GL-0001', cas_number:'154-17-6', formula:'C6H12O5', molecular_weight:'164.16', purity:'HPLC-99%', appearance:'White crystalline powder', solubility:'Water', storage:'RT', synonyms:'2-DG; 2-Deoxyglucose', description:'Glucose analog that inhibits glycolysis; used to study the Warburg effect in cancer cells.', category_id:'3', image_url:null, price_min:20, price_max:75, created_at:'' },
  { id:'182', name:'Lonidamine', slug:'lonidamine', catalog_number:'VD-GL-0002', cas_number:'50264-69-2', formula:'C15H10Cl2N2O2', molecular_weight:'321.16', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'RT', synonyms:'Doridamina', description:'Hexokinase II inhibitor; disrupts mitochondria-associated glycolysis in tumor cells.', category_id:'3', image_url:null, price_min:40, price_max:155, created_at:'' },
  { id:'183', name:'Oxamate sodium', slug:'oxamate-sodium', catalog_number:'VD-GL-0003', cas_number:'565-73-1', formula:'C2H2NNaO3', molecular_weight:'111.03', purity:'HPLC-98%', appearance:'White powder', solubility:'Water', storage:'RT', synonyms:'Sodium oxamate; LDH inhibitor', description:'Lactate dehydrogenase (LDH) inhibitor; blocks anaerobic glycolysis in tumor cells.', category_id:'3', image_url:null, price_min:25, price_max:95, created_at:'' },
  // ── GLUTAMINE METABOLISM ─────────────────────────────────────────────────
  { id:'184', name:'BPTES', slug:'bptes', catalog_number:'VD-GM-0001', cas_number:'314045-39-1', formula:'C20H22N4O2S2', molecular_weight:'418.54', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'GLS1 inhibitor', description:'Allosteric glutaminase (GLS1) inhibitor; blocks glutamine-dependent cancer cell growth.', category_id:'3', image_url:null, price_min:80, price_max:310, created_at:'' },
  { id:'185', name:'CB-839', slug:'cb-839', catalog_number:'VD-GM-0002', cas_number:'1439399-58-2', formula:'C21H19F3N4O3S', molecular_weight:'468.46', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'Telaglenastat; GLS inhibitor', description:'Potent selective glutaminase inhibitor in clinical trials for solid tumors.', category_id:'3', image_url:null, price_min:95, price_max:370, created_at:'' },
  // ── ARGININE METABOLISM ──────────────────────────────────────────────────
  { id:'186', name:'Nor-NOHA acetate', slug:'nor-noha-acetate', catalog_number:'VD-AM2-0001', cas_number:'115041-48-0', formula:'C6H14N4O3·C2H4O2', molecular_weight:'278.31', purity:'HPLC-97%', appearance:'White solid', solubility:'Water', storage:'-20°C', synonyms:'Arginase inhibitor I', description:'Potent competitive arginase inhibitor; used in nitric oxide and immune metabolism research.', category_id:'4', image_url:null, price_min:75, price_max:290, created_at:'' },
  { id:'187', name:'L-NAME HCl', slug:'l-name-hcl', catalog_number:'VD-AM2-0002', cas_number:'51298-62-5', formula:'C7H15N4O4·HCl·0.5H2O', molecular_weight:'287.68', purity:'HPLC-99%', appearance:'White crystalline powder', solubility:'Water', storage:'-20°C', synonyms:'Nω-Nitro-L-arginine methyl ester', description:'Pan-NOS inhibitor; blocks nitric oxide synthesis; induces hypertension in animal models.', category_id:'4', image_url:null, price_min:25, price_max:95, created_at:'' },
  // ── IDO / TRYPTOPHAN ─────────────────────────────────────────────────────
  { id:'188', name:'1-Methyl-DL-tryptophan', slug:'1-methyl-dl-tryptophan', catalog_number:'VD-TR-0001', cas_number:'59820-43-8', formula:'C12H14N2O2', molecular_weight:'218.25', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'RT', synonyms:'1-MT; IDO inhibitor', description:'IDO1 inhibitor; blocks kynurenine pathway; used in tumor immunology research.', category_id:'3', image_url:null, price_min:35, price_max:135, created_at:'' },
  // ── PROTEOMICS TOOLS ────────────────────────────────────────────────────
  { id:'189', name:'Bortezomib analog MG-132', slug:'ps341-mg132', catalog_number:'VD-PT-0001', cas_number:'110044-82-1', formula:'C25H32BN3O5', molecular_weight:'477.35', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'PS-341 research grade', description:'20S proteasome inhibitor reference standard for proteomic flux experiments.', category_id:'4', image_url:null, price_min:85, price_max:330, created_at:'' },
  { id:'190', name:'Cycloheximide', slug:'cycloheximide', catalog_number:'VD-PT-0002', cas_number:'66-81-9', formula:'C15H23NO4', molecular_weight:'281.35', purity:'HPLC-98%', appearance:'White to off-white powder', solubility:'Ethanol', storage:'-20°C', synonyms:'Actidione', description:'Eukaryotic protein synthesis inhibitor (60S ribosome); used to measure protein half-lives.', category_id:'5', image_url:null, price_min:30, price_max:115, created_at:'' },
  { id:'191', name:'Puromycin aminonucleoside', slug:'puromycin-aminonucleoside', catalog_number:'VD-PT-0003', cas_number:'58-60-6', formula:'C12H18N6O4', molecular_weight:'298.31', purity:'HPLC-97%', appearance:'White powder', solubility:'Water', storage:'-20°C', synonyms:'PAN; NSC 3056', description:'Aminonucleoside portion of puromycin; used as nephrotoxic model compound.', category_id:'5', image_url:null, price_min:45, price_max:175, created_at:'' },
  // ── LIPID KINASES ────────────────────────────────────────────────────────
  { id:'192', name:'GDC-0941', slug:'gdc-0941', catalog_number:'VD-LK-0001', cas_number:'957054-30-7', formula:'C23H27N7O3S', molecular_weight:'497.57', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'Pictilisib; PI3K inhibitor', description:'Potent pan-class I PI3K inhibitor; blocks PI3Kα/β/δ/γ.', category_id:'3', image_url:null, price_min:85, price_max:330, created_at:'' },
  { id:'193', name:'BKM120', slug:'bkm120', catalog_number:'VD-LK-0002', cas_number:'944396-07-0', formula:'C17H19FN6O', molecular_weight:'354.37', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'Buparlisib; NVP-BKM120', description:'Oral pan-class I PI3K inhibitor in clinical trials for multiple tumor types.', category_id:'3', image_url:null, price_min:85, price_max:330, created_at:'' },
  { id:'194', name:'AKT inhibitor VIII', slug:'akt-inhibitor-viii', catalog_number:'VD-LK-0003', cas_number:'612847-09-3', formula:'C25H28N4O3', molecular_weight:'436.52', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'Akti-1/2', description:'Allosteric AKT1/2 inhibitor; blocks PH domain membrane recruitment.', category_id:'4', image_url:null, price_min:80, price_max:310, created_at:'' },
  { id:'195', name:'MK-2206 dihydrochloride', slug:'mk-2206-dihydrochloride', catalog_number:'VD-LK-0004', cas_number:'1032350-13-2', formula:'C25H24N4O·2HCl', molecular_weight:'481.41', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'Pan-AKT inhibitor', description:'Highly selective allosteric AKT inhibitor; antitumor and sensitizes to chemotherapy.', category_id:'3', image_url:null, price_min:85, price_max:330, created_at:'' },
  // ── ANDROGEN / PROSTATE ──────────────────────────────────────────────────
  { id:'196', name:'Enzalutamide', slug:'enzalutamide', catalog_number:'VD-PR-0001', cas_number:'915087-33-1', formula:'C21H16F4N4O2S', molecular_weight:'464.44', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'MDV3100; Xtandi', description:'Second-generation androgen receptor antagonist; approved for castration-resistant prostate cancer.', category_id:'3', image_url:null, price_min:90, price_max:350, created_at:'' },
  { id:'197', name:'Abiraterone acetate', slug:'abiraterone-acetate', catalog_number:'VD-PR-0002', cas_number:'154229-19-3', formula:'C26H33NO2', molecular_weight:'391.55', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'CB7630; Zytiga', description:'CYP17A1 inhibitor; blocks androgen biosynthesis in prostate cancer.', category_id:'3', image_url:null, price_min:75, price_max:290, created_at:'' },
  // ── BREAST / ESTROGEN ────────────────────────────────────────────────────
  { id:'198', name:'Fulvestrant', slug:'fulvestrant', catalog_number:'VD-BR-0001', cas_number:'129453-61-8', formula:'C32H47F5O3S', molecular_weight:'606.77', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'ICI 182780; Faslodex', description:'Selective estrogen receptor degrader (SERD); pure ER antagonist with no agonist activity.', category_id:'3', image_url:null, price_min:85, price_max:330, created_at:'' },
  { id:'199', name:'Letrozole', slug:'letrozole', catalog_number:'VD-BR-0002', cas_number:'112809-51-5', formula:'C17H11N5', molecular_weight:'285.30', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'RT', synonyms:'Femara; CGS 20267', description:'Non-steroidal aromatase inhibitor; blocks estrogen synthesis in breast cancer.', category_id:'3', image_url:null, price_min:35, price_max:135, created_at:'' },
  { id:'200', name:'Anastrozole', slug:'anastrozole', catalog_number:'VD-BR-0003', cas_number:'120511-73-1', formula:'C17H19N5', molecular_weight:'293.37', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'RT', synonyms:'Arimidex; ZD1033', description:'Selective non-steroidal aromatase inhibitor; first-line for postmenopausal breast cancer.', category_id:'3', image_url:null, price_min:35, price_max:135, created_at:'' },
  // ── RNA / TRANSCRIPTION ──────────────────────────────────────────────────
  { id:'201', name:'Actinomycin D', slug:'actinomycin-d', catalog_number:'VD-TX-0001', cas_number:'50-76-0', formula:'C62H86N12O16', molecular_weight:'1255.42', purity:'HPLC-98%', appearance:'Red powder', solubility:'Ethanol', storage:'-20°C', synonyms:'Dactinomycin; DACT', description:'DNA intercalator that inhibits RNA polymerase; blocks transcription.', category_id:'3', image_url:null, price_min:40, price_max:155, created_at:'' },
  { id:'202', name:'α-Amanitin', slug:'alpha-amanitin', catalog_number:'VD-TX-0002', cas_number:'23109-05-9', formula:'C39H54N10O14S', molecular_weight:'919.00', purity:'HPLC-95%', appearance:'White powder', solubility:'Water', storage:'-20°C', synonyms:'RNA Pol II inhibitor', description:'Bicyclic heptapeptide toxin; highly selective RNA polymerase II inhibitor.', category_id:'4', image_url:null, price_min:120, price_max:470, created_at:'' },
  { id:'203', name:'DRB', slug:'drb', catalog_number:'VD-TX-0003', cas_number:'53-85-0', formula:'C10H11BrN2O5', molecular_weight:'351.11', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'5,6-Dichloro-1-β-D-ribofuranosylbenzimidazole', description:'CK2 and CDK9 inhibitor; blocks RNA Pol II elongation; used in transcription studies.', category_id:'4', image_url:null, price_min:55, price_max:210, created_at:'' },
  // ── NUCLEAR TRANSPORT ────────────────────────────────────────────────────
  { id:'204', name:'Leptomycin B', slug:'leptomycin-b', catalog_number:'VD-NT-0001', cas_number:'87081-35-4', formula:'C33H47NaO6', molecular_weight:'566.71', purity:'HPLC-95%', appearance:'Clear to yellow oil', solubility:'Ethanol', storage:'-80°C', synonyms:'CRM1/XPO1 inhibitor', description:'Irreversible CRM1 nuclear export receptor inhibitor; traps proteins in the nucleus.', category_id:'4', image_url:null, price_min:110, price_max:430, created_at:'' },
  { id:'205', name:'KPT-330', slug:'kpt-330', catalog_number:'VD-NT-0002', cas_number:'1393477-72-9', formula:'C20H17F6N3O', molecular_weight:'443.36', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'Selinexor; XPO1 inhibitor', description:'Selective inhibitor of nuclear export (SINE); FDA-approved for multiple myeloma.', category_id:'3', image_url:null, price_min:95, price_max:370, created_at:'' },
  // ── UNFOLDED PROTEIN RESPONSE ────────────────────────────────────────────
  { id:'206', name:'Tunicamycin', slug:'tunicamycin', catalog_number:'VD-UPR-0001', cas_number:'11089-65-9', formula:'C39H64N4O16', molecular_weight:'861.94', purity:'HPLC-95%', appearance:'White powder', solubility:'DMSO', storage:'-20°C', synonyms:'Mycospocidin', description:'N-glycosylation inhibitor; potent ER stress inducer; activates all three UPR branches.', category_id:'4', image_url:null, price_min:55, price_max:210, created_at:'' },
  { id:'207', name:'Thapsigargin', slug:'thapsigargin', catalog_number:'VD-UPR-0002', cas_number:'67526-95-8', formula:'C34H50O12', molecular_weight:'650.74', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'SERCA inhibitor', description:'Irreversible SERCA Ca2+-ATPase inhibitor; depletes ER calcium stores inducing UPR.', category_id:'4', image_url:null, price_min:75, price_max:290, created_at:'' },
  { id:'208', name:'GSK2606414', slug:'gsk2606414', catalog_number:'VD-UPR-0003', cas_number:'1337531-36-8', formula:'C23H22FN5O3', molecular_weight:'451.45', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'PERK inhibitor I', description:'Selective PERK (EIF2AK3) kinase inhibitor; blocks the UPR PERK/eIF2α branch.', category_id:'4', image_url:null, price_min:90, price_max:350, created_at:'' },
  // ── MISCELLANEOUS BIOACTIVE ──────────────────────────────────────────────
  { id:'209', name:'Colchicine', slug:'colchicine', catalog_number:'VD-MB-0001', cas_number:'64-86-8', formula:'C22H25NO6', molecular_weight:'399.44', purity:'HPLC-99%', appearance:'Yellow powder', solubility:'Ethanol', storage:'RT', synonyms:'Colchicum extract', description:'Tubulin polymerization inhibitor; arrests cells in metaphase; anti-gout and anti-inflammatory.', category_id:'4', image_url:null, price_min:25, price_max:95, created_at:'' },
  { id:'210', name:'Phorbol 12-myristate 13-acetate', slug:'phorbol-12-myristate-13-acetate', catalog_number:'VD-MB-0002', cas_number:'16561-29-8', formula:'C36H56O8', molecular_weight:'616.83', purity:'HPLC-98%', appearance:'White solid', solubility:'DMSO', storage:'-20°C', synonyms:'PMA; TPA; PKC activator', description:'Potent PKC activator and tumor promoter; induces monocyte/macrophage differentiation.', category_id:'4', image_url:null, price_min:55, price_max:210, created_at:'' },
]

export const CATEGORIES = [
  { id:'1', name:'Antivirals', slug:'antivirals' },
  { id:'2', name:'Apoptosis', slug:'apoptosis' },
  { id:'3', name:'Cancer Research', slug:'cancer' },
  { id:'4', name:'Enzyme Inhibitors', slug:'enzyme-inhibitors' },
  { id:'5', name:'Antibiotics', slug:'antibiotics' },
  { id:'6', name:'DNA Damage/Repair', slug:'dna-damage-repair' },
  { id:'7', name:'Cholinergics', slug:'cholinergics' },
  { id:'8', name:'Anticoagulants', slug:'anticoagulants' },
  { id:'9', name:'Intermediates & Fine Chemicals', slug:'intermediates-fine-chemicals' },
  { id:'10', name:'Histaminergics', slug:'histaminergics' },
  { id:'11', name:'Inorganics', slug:'inorganics' },
]